import { faker } from "@faker-js/faker"
import type { CreateAuthTokenResult } from "@src/db/auth_tokens"
import { create as createAuthToken } from "@src/db/auth_tokens"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface AuthTokenFactoryParams {
  email?: string
}

/**
 * Factory for building test auth token data
 */
const factory = Factory.define<CreateAuthTokenResult, AuthTokenFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  email: params.email ?? faker.internet.email(),
  otpCode: "000000", // Will be generated by createAuthToken
  sessionToken: "", // Will be generated by createAuthToken
  expiresAt: new Date(Date.now() + 15 * 60 * 1000),
}))

/**
 * Create a test auth token in the database
 * Usage:
 *   const token = await authTokenFactory.create({}, testCtx.db)
 *   const token = await authTokenFactory.create({ email: 'test@example.com' }, testCtx.db)
 */
export const authTokenFactory = {
  build: factory.build.bind(factory),
  create: async (
    params: Partial<AuthTokenFactoryParams>,
    db: SQL
  ): Promise<CreateAuthTokenResult> => {
    const built = factory.build(params)
    return await createAuthToken(db, built.email)
  },
}
