import { faker } from "@faker-js/faker"
import type { CampaignCharacter } from "@src/db/campaign_characters"
import { create as createCampaignCharacterDb } from "@src/db/campaign_characters"
import type { CampaignMember, CampaignMemberRole } from "@src/db/campaign_members"
import { create as createCampaignMemberDb } from "@src/db/campaign_members"
import type { Campaign, CreateCampaign } from "@src/db/campaigns"
import { create as createCampaign } from "@src/db/campaigns"
import { ulid } from "@src/lib/ids"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface CampaignFactoryParams {
  name?: string
  description?: string | null
  created_by: string
}

/**
 * Factory for building test campaign data
 */
const factory = Factory.define<Campaign, CampaignFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  name: params.name ?? `${faker.word.adjective()} ${faker.word.noun()} Campaign`,
  description: params.description === undefined ? faker.lorem.sentence() : params.description,
  created_by: params.created_by ?? "",
  archived_at: null,
  created_at: new Date(),
  updated_at: new Date(),
}))

/**
 * Create a test campaign in the database
 * Usage:
 *   const campaign = await campaignFactory.create({ created_by: user.id }, testCtx.db)
 *   const campaign = await campaignFactory.create({ created_by: user.id, name: 'My Campaign' }, testCtx.db)
 */
export const campaignFactory = {
  build: factory.build.bind(factory),
  create: async (params: CampaignFactoryParams, db: SQL): Promise<Campaign> => {
    const built = factory.build(params)

    if (!built.created_by) {
      throw new Error("created_by is required to create a campaign")
    }

    const campaignData: CreateCampaign = {
      name: built.name,
      description: built.description,
      created_by: built.created_by,
    }

    const campaign = await createCampaign(db, campaignData)

    // Add creator as DM member (same as create service does)
    await createCampaignMemberDb(db, {
      campaign_id: campaign.id,
      user_id: built.created_by,
      role: "dm",
      invite_token: null,
      invited_by: built.created_by,
      accepted_at: new Date(),
      declined_at: null,
    })

    return campaign
  },
}

interface CampaignMemberFactoryParams {
  campaign_id: string
  user_id: string
  role?: CampaignMemberRole
  invited_by: string
  // If true, generates an invite_token (for pending invites)
  pending?: boolean
}

/**
 * Create a test campaign member in the database
 * Usage:
 *   // Accepted member (default)
 *   await campaignMemberFactory.create({ campaign_id, user_id, invited_by }, db)
 *
 *   // Pending invite
 *   await campaignMemberFactory.create({ campaign_id, user_id, invited_by, pending: true }, db)
 */
export const campaignMemberFactory = {
  create: async (params: CampaignMemberFactoryParams, db: SQL): Promise<CampaignMember> => {
    const isPending = params.pending ?? false

    return await createCampaignMemberDb(db, {
      campaign_id: params.campaign_id,
      user_id: params.user_id,
      role: params.role ?? "player",
      invite_token: isPending ? ulid() : null,
      invited_by: params.invited_by,
      accepted_at: isPending ? null : new Date(),
      declined_at: null,
    })
  },
}

interface CampaignCharacterFactoryParams {
  campaign_id: string
  character_id: string
  added_by: string
  revealed_at?: Date | null
}

/**
 * Create a test campaign character in the database
 * Usage:
 *   await campaignCharacterFactory.create({ campaign_id, character_id, added_by }, db)
 */
export const campaignCharacterFactory = {
  create: async (params: CampaignCharacterFactoryParams, db: SQL): Promise<CampaignCharacter> => {
    return await createCampaignCharacterDb(db, {
      campaign_id: params.campaign_id,
      character_id: params.character_id,
      added_by: params.added_by,
      // Use explicit undefined check to allow null for hidden NPCs
      revealed_at: params.revealed_at !== undefined ? params.revealed_at : new Date(),
    })
  },
}
