import { faker } from "@faker-js/faker"
import { create as createCampaignMemberDb } from "@src/db/campaign_members"
import type { Campaign, CreateCampaign } from "@src/db/campaigns"
import { create as createCampaign } from "@src/db/campaigns"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface CampaignFactoryParams {
  name?: string
  description?: string | null
  created_by: string
}

/**
 * Factory for building test campaign data
 */
const factory = Factory.define<Campaign, CampaignFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  name: params.name ?? `${faker.word.adjective()} ${faker.word.noun()} Campaign`,
  description: params.description === undefined ? faker.lorem.sentence() : params.description,
  created_by: params.created_by ?? "",
  archived_at: null,
  created_at: new Date(),
  updated_at: new Date(),
}))

/**
 * Create a test campaign in the database
 * Usage:
 *   const campaign = await campaignFactory.create({ created_by: user.id }, testCtx.db)
 *   const campaign = await campaignFactory.create({ created_by: user.id, name: 'My Campaign' }, testCtx.db)
 */
export const campaignFactory = {
  build: factory.build.bind(factory),
  create: async (params: CampaignFactoryParams, db: SQL): Promise<Campaign> => {
    const built = factory.build(params)

    if (!built.created_by) {
      throw new Error("created_by is required to create a campaign")
    }

    const campaignData: CreateCampaign = {
      name: built.name,
      description: built.description,
      created_by: built.created_by,
    }

    const campaign = await createCampaign(db, campaignData)

    // Add creator as DM member (same as create service does)
    await createCampaignMemberDb(db, {
      campaign_id: campaign.id,
      user_id: built.created_by,
      role: "dm",
      invited_by: built.created_by,
      accepted_at: new Date(),
      declined_at: null,
    })

    return campaign
  },
}
