import { faker } from "@faker-js/faker"
import type { Character, CreateCharacter } from "@src/db/characters"
import { create as createCharacter } from "@src/db/characters"
import type { RulesetId } from "@src/lib/dnd/rulesets"
import { SRD51_ID } from "@src/lib/dnd/srd51"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface CharacterFactoryParams {
  user_id?: string
  name?: string
  species?: string
  lineage?: string | null
  background?: string
  alignment?: string | null
  ruleset?: RulesetId
}

const species = [
  "human",
  "elf",
  "dwarf",
  "halfling",
  "dragonborn",
  "gnome",
  "half-elf",
  "half-orc",
  "tiefling",
]
const backgrounds = [
  "acolyte",
  "criminal",
  "folk hero",
  "noble",
  "sage",
  "soldier",
  "urchin",
  "entertainer",
]
const alignments = [
  "Lawful Good",
  "Neutral Good",
  "Chaotic Good",
  "Lawful Neutral",
  "True Neutral",
  "Chaotic Neutral",
  "Lawful Evil",
  "Neutral Evil",
  "Chaotic Evil",
]

/**
 * Factory for building test character data
 */
const factory = Factory.define<Character, CharacterFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  user_id: params.user_id ?? "", // Required - will throw error if not provided
  name: params.name ?? faker.person.firstName(),
  species: params.species ?? faker.helpers.arrayElement(species),
  lineage: params.lineage === undefined ? null : params.lineage,
  background: params.background ?? faker.helpers.arrayElement(backgrounds),
  alignment:
    params.alignment === undefined ? faker.helpers.arrayElement(alignments) : params.alignment,
  ruleset: params.ruleset ?? SRD51_ID,
  avatar_id: null,
  created_at: new Date(),
  updated_at: new Date(),
}))

/**
 * Create a test character in the database
 * Usage:
 *   const character = await characterFactory.create({ user_id: user.id }, testCtx.db)
 *   const character = await characterFactory.create({ user_id: user.id, name: 'Aragorn' }, testCtx.db)
 */
export const characterFactory = {
  build: factory.build.bind(factory),
  create: async (params: Partial<CharacterFactoryParams>, db: SQL): Promise<Character> => {
    const built = factory.build(params)

    if (!built.user_id) {
      throw new Error("user_id is required to create a character")
    }

    const characterData: CreateCharacter = {
      user_id: built.user_id,
      name: built.name,
      species: built.species,
      lineage: built.lineage,
      background: built.background,
      alignment: built.alignment,
      ruleset: built.ruleset,
      avatar_id: null,
    }

    return await createCharacter(db, characterData)
  },
}
