import { faker } from "@faker-js/faker"
import type { CharBeastSeen, CreateCharBeastSeen } from "@src/db/char_beasts_seen"
import { create as createBeastSeen } from "@src/db/char_beasts_seen"
import { getBeasts } from "@src/lib/dnd/beasts"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface CharBeastSeenFactoryParams {
  character_id?: string
  beast_id?: string
  note?: string | null
}

/**
 * Factory for building test seen beast data
 */
const factory = Factory.define<CharBeastSeen, CharBeastSeenFactoryParams>(({ params }) => {
  // Get a random beast from srd52 (default for tests)
  const beasts = getBeasts("srd52")
  const randomBeast = faker.helpers.arrayElement(beasts)

  return {
    id: "", // Will be generated by the database
    character_id: params.character_id ?? "", // Required - will throw error if not provided
    beast_id: params.beast_id ?? randomBeast.id,
    note: params.note ?? null,
    replaced_at: null,
    replaced_by: null,
    created_at: new Date(),
    updated_at: new Date(),
  }
})

/**
 * Create a test seen beast in the database
 * Usage:
 *   const beastSeen = await charBeastSeenFactory.create({ character_id: character.id }, testCtx.db)
 *   const beastSeen = await charBeastSeenFactory.create({ character_id: character.id, beast_id: 'srd52_wolf' }, testCtx.db)
 */
export const charBeastSeenFactory = {
  build: factory.build.bind(factory),
  create: async (params: Partial<CharBeastSeenFactoryParams>, db: SQL): Promise<CharBeastSeen> => {
    const built = factory.build(params)

    if (!built.character_id) {
      throw new Error("character_id is required to create a seen beast")
    }

    const beastSeenData: CreateCharBeastSeen = {
      character_id: built.character_id,
      beast_id: built.beast_id,
      note: built.note,
    }

    return createBeastSeen(db, beastSeenData)
  },
}
