import { faker } from "@faker-js/faker"
import type { Character, CreateCharacter } from "@src/db/characters"
import { create } from "@src/db/characters"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface CharacterFactoryParams {
  user_id?: string
  name?: string
  race?: string
  subrace?: string | null
  background?: string
  alignment?: string | null
  ruleset?: "srd51" | "srd52"
}

/**
 * Factory for creating test characters
 * Usage:
 *   const character = await characterFactory.create(db, { user_id: user.id })
 *   const character = await characterFactory.create(db, { user_id: user.id, name: 'Aragorn' })
 */
class CharacterFactory extends Factory<Character, CharacterFactoryParams, SQL> {
  async create(transientParams?: Partial<CharacterFactoryParams>, db?: SQL): Promise<Character> {
    if (!db) {
      throw new Error("Database connection is required to create a character")
    }

    if (!transientParams?.user_id) {
      throw new Error("user_id is required to create a character")
    }

    const params = this.build(transientParams)

    const characterData: CreateCharacter = {
      user_id: params.user_id!,
      name: params.name,
      race: params.race,
      subrace: params.subrace,
      background: params.background,
      alignment: params.alignment,
      ruleset: params.ruleset,
    }

    return await create(db, characterData)
  }
}

const races = [
  "Human",
  "Elf",
  "Dwarf",
  "Halfling",
  "Dragonborn",
  "Gnome",
  "Half-Elf",
  "Half-Orc",
  "Tiefling",
]
const backgrounds = [
  "Acolyte",
  "Criminal",
  "Folk Hero",
  "Noble",
  "Sage",
  "Soldier",
  "Urchin",
  "Entertainer",
]
const alignments = [
  "Lawful Good",
  "Neutral Good",
  "Chaotic Good",
  "Lawful Neutral",
  "True Neutral",
  "Chaotic Neutral",
  "Lawful Evil",
  "Neutral Evil",
  "Chaotic Evil",
]

export const characterFactory = CharacterFactory.define(({ params }) => ({
  id: "", // Will be generated by the database
  user_id: params.user_id ?? "", // Required - will throw error if not provided
  name: params.name ?? faker.person.firstName(),
  race: params.race ?? faker.helpers.arrayElement(races),
  subrace: params.subrace === undefined ? null : params.subrace,
  background: params.background ?? faker.helpers.arrayElement(backgrounds),
  alignment:
    params.alignment === undefined ? faker.helpers.arrayElement(alignments) : params.alignment,
  ruleset: params.ruleset ?? "srd51",
  created_at: new Date(),
  updated_at: new Date(),
}))
