import { faker } from "@faker-js/faker"
import type { CharWildShapeUse, CreateCharWildShapeUse } from "@src/db/char_wild_shape_uses"
import { create as createWildShapeUse } from "@src/db/char_wild_shape_uses"
import { getBeasts } from "@src/lib/dnd/beasts"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface CharWildShapeUseFactoryParams {
  character_id?: string
  beast_id?: string
  note?: string | null
}

/**
 * Factory for building test wild shape use data
 */
const factory = Factory.define<CharWildShapeUse, CharWildShapeUseFactoryParams>(({ params }) => {
  // Get a random beast from srd52 (default for tests)
  const beasts = getBeasts("srd52")
  const randomBeast = faker.helpers.arrayElement(beasts)

  return {
    id: "", // Will be generated by the database
    character_id: params.character_id ?? "", // Required - will throw error if not provided
    beast_id: params.beast_id ?? randomBeast.id,
    ended_at: null,
    recovered_at: null,
    note: params.note ?? null,
    created_at: new Date(),
    updated_at: new Date(),
  }
})

/**
 * Create a test wild shape use in the database
 * Usage:
 *   const use = await charWildShapeUseFactory.create({ character_id: character.id }, testCtx.db)
 *   const use = await charWildShapeUseFactory.create({ character_id: character.id, beast_id: 'srd52_wolf' }, testCtx.db)
 */
export const charWildShapeUseFactory = {
  build: factory.build.bind(factory),
  create: async (
    params: Partial<CharWildShapeUseFactoryParams>,
    db: SQL
  ): Promise<CharWildShapeUse> => {
    const built = factory.build(params)

    if (!built.character_id) {
      throw new Error("character_id is required to create a wild shape use")
    }

    const useData: CreateCharWildShapeUse = {
      character_id: built.character_id,
      beast_id: built.beast_id,
      note: built.note,
    }

    return createWildShapeUse(db, useData)
  },
}
