import { faker } from "@faker-js/faker"
import type { Upload } from "@src/db/uploads"
import { ALLOWED_IMAGE_TYPES, create as createUpload, UploadStatus } from "@src/db/uploads"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface UploadFactoryParams {
  user_id?: string
  status?: "pending" | "complete" | "failed"
  content_type?: string
  size_bytes?: number
  original_filename?: string
}

/**
 * Factory for building test upload data
 */
const factory = Factory.define<Upload, UploadFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  user_id: params.user_id ?? "",
  status: (params.status ?? UploadStatus.PENDING) as "pending" | "complete" | "failed",
  content_type: params.content_type ?? faker.helpers.arrayElement([...ALLOWED_IMAGE_TYPES]),
  size_bytes: params.size_bytes ?? faker.number.int({ min: 1000, max: 5000000 }),
  original_filename: params.original_filename ?? faker.system.fileName(),
  s3_key: null,
  created_at: new Date(),
  completed_at: null,
}))

/**
 * Create a test upload in the database
 * Usage:
 *   const upload = await uploadFactory.create({ user_id: user.id }, testCtx.db)
 *   const upload = await uploadFactory.create({ user_id: user.id, status: 'complete' }, testCtx.db)
 */
export const uploadFactory = {
  build: factory.build.bind(factory),
  create: async (params: Partial<UploadFactoryParams>, db: SQL): Promise<Upload> => {
    const built = factory.build(params)
    return await createUpload(db, {
      user_id: built.user_id,
      content_type: built.content_type as (typeof ALLOWED_IMAGE_TYPES)[number],
      size_bytes: built.size_bytes ?? 1000,
      original_filename: built.original_filename ?? undefined,
    })
  },
}
