import { faker } from "@faker-js/faker"
import type { User } from "@src/db/users"
import { create } from "@src/db/users"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface UserFactoryParams {
  email?: string
}

/**
 * Factory for creating test users
 * Usage:
 *   const user = await userFactory.create(db)
 *   const user = await userFactory.create(db, { email: 'custom@example.com' })
 */
class UserFactory extends Factory<User, UserFactoryParams, SQL> {
  async create(transientParams?: Partial<UserFactoryParams>, db?: SQL): Promise<User> {
    if (!db) {
      throw new Error("Database connection is required to create a user")
    }

    const params = this.build(transientParams)
    return await create(db, params.email)
  }
}

export const userFactory = UserFactory.define(({ params }) => ({
  id: "", // Will be generated by the database
  email: params.email ?? faker.internet.email(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}))
