import { faker } from "@faker-js/faker"
import type { User } from "@src/db/users"
import { create as createUser } from "@src/db/users"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface UserFactoryParams {
  email?: string
}

/**
 * Factory for building test user data
 */
const factory = Factory.define<User, UserFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  email: params.email ?? faker.internet.email(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}))

/**
 * Create a test user in the database
 * Usage:
 *   const user = await userFactory.create({}, testCtx.db)
 *   const user = await userFactory.create({ email: 'custom@example.com' }, testCtx.db)
 */
export const userFactory = {
  build: factory.build.bind(factory),
  create: async (params: Partial<UserFactoryParams>, db: SQL): Promise<User> => {
    const built = factory.build(params)
    return await createUser(db, built.email)
  },
}
