import { faker } from "@faker-js/faker"
import type { User } from "@src/db/users"
import { create as createUser, markWelcomed } from "@src/db/users"
import type { SQL } from "bun"
import { Factory } from "fishery"

interface UserFactoryParams {
  email?: string
  name?: string | null
}

/**
 * Factory for building test user data
 */
const factory = Factory.define<User, UserFactoryParams>(({ params }) => ({
  id: "", // Will be generated by the database
  email: params.email ?? faker.internet.email(),
  name: params.name ?? null,
  marketing_opt_in: true,
  welcomed_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}))

/**
 * Create a test user in the database
 * Usage:
 *   const user = await userFactory.create({}, testCtx.db)
 *   const user = await userFactory.create({ email: 'custom@example.com' }, testCtx.db)
 */
export const userFactory = {
  build: factory.build.bind(factory),
  create: async (params: Partial<UserFactoryParams>, db: SQL): Promise<User> => {
    const built = factory.build(params)
    const user = await createUser(db, built.email)
    // Mark as welcomed so tests don't trigger the welcome page guard
    await markWelcomed(db, user.id)
    return { ...user, welcomed_at: new Date().toISOString() }
  },
}
