import type { Beast } from "../beasts"

export const srd51Beasts: Beast[] = [
  {
    id: "srd51_ape",
    name: "Ape",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 12,
    hitPoints: 19,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 16,
      dexterity: 14,
      constitution: 14,
      intelligence: 6,
      wisdom: 12,
      charisma: 7,
    },
    skills: { athletics: 5, perception: 3 },
    senses: "passive Perception 13",
    actions: [
      {
        name: "Fist",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 3 },
      },
      {
        name: "Rock",
        attackType: "ranged",
        attackBonus: 5,
        range: { normal: 25, long: 50 },
        damage: { type: "bludgeoning", dice: [6], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_axe_beak",
    name: "Axe Beak",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 11,
    hitPoints: 19,
    speed: { walk: 50 },
    abilities: {
      strength: 14,
      dexterity: 12,
      constitution: 12,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", dice: [8], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_baboon",
    name: "Baboon",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 8,
      dexterity: 14,
      constitution: 11,
      intelligence: 4,
      wisdom: 12,
      charisma: 6,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The baboon has advantage on an attack roll against a creature if at least one of the baboon's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 1,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: -1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_badger",
    name: "Badger",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 3,
    speed: { walk: 20, burrow: 5 },
    abilities: {
      strength: 4,
      dexterity: 11,
      constitution: 12,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    senses: "darkvision 30 ft., passive Perception 11",
    traits: [
      {
        name: "Keen Smell",
        description: "The badger has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_bat",
    name: "Bat",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 1,
    speed: { walk: 5, fly: 30 },
    abilities: {
      strength: 2,
      dexterity: 15,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 4,
    },
    senses: "blindsight 60 ft., passive Perception 11",
    traits: [
      {
        name: "Echolocation",
        description: "The bat can't use its blindsight while deafened.",
      },
      {
        name: "Keen Hearing",
        description: "The bat has advantage on Wisdom (Perception) checks that rely on hearing.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_black_bear",
    name: "Black Bear",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 11,
    acType: "natural armor",
    hitPoints: 19,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 15,
      dexterity: 10,
      constitution: 14,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The bear has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
      },
      {
        name: "Claws",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "slashing", dice: [4, 4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_blood_hawk",
    name: "Blood Hawk",
    size: "small",
    cr: 0.125,
    xp: 25,
    ac: 12,
    hitPoints: 7,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 6,
      dexterity: 14,
      constitution: 10,
      intelligence: 3,
      wisdom: 14,
      charisma: 5,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    traits: [
      {
        name: "Keen Sight",
        description: "The hawk has advantage on Wisdom (Perception) checks that rely on sight.",
      },
      {
        name: "Pack Tactics",
        description:
          "The hawk has advantage on an attack roll against a creature if at least one of the hawk's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_boar",
    name: "Boar",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 11,
    acType: "natural armor",
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 13,
      dexterity: 11,
      constitution: 12,
      intelligence: 2,
      wisdom: 9,
      charisma: 5,
    },
    senses: "passive Perception 9",
    traits: [
      {
        name: "Charge",
        description:
          "If the boar moves at least 20 feet straight toward a target and then hits it with a tusk attack on the same turn, the target takes an extra 3 (1d6) slashing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.",
      },
      {
        name: "Relentless",
        description:
          "If the boar takes 7 damage or less that would reduce it to 0 hit points, it is reduced to 1 hit point instead. Recharges after a short or long rest.",
      },
    ],
    actions: [
      {
        name: "Tusk",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "slashing", dice: [6], flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_brown_bear",
    name: "Brown Bear",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 11,
    acType: "natural armor",
    hitPoints: 34,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 19,
      dexterity: 10,
      constitution: 16,
      intelligence: 2,
      wisdom: 13,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The bear has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 4 },
      },
      {
        name: "Claws",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 4 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_camel",
    name: "Camel",
    size: "large",
    cr: 0.125,
    xp: 25,
    ac: 9,
    hitPoints: 15,
    speed: { walk: 50 },
    abilities: {
      strength: 16,
      dexterity: 8,
      constitution: 14,
      intelligence: 2,
      wisdom: 8,
      charisma: 5,
    },
    senses: "passive Perception 9",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4] },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_cat",
    name: "Cat",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 2,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 3,
      dexterity: 15,
      constitution: 10,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The cat has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Claws",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "slashing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_constrictor_snake",
    name: "Constrictor Snake",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 12,
    hitPoints: 13,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 14,
      constitution: 12,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    senses: "blindsight 10 ft., passive Perception 10",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
      },
      {
        name: "Constrict",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [8], flatBonus: 2 },
        description: "Target is grappled (escape DC 14) and restrained until the grapple ends.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_crab",
    name: "Crab",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    acType: "natural armor",
    hitPoints: 2,
    speed: { walk: 20, swim: 20 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 10,
      intelligence: 1,
      wisdom: 8,
      charisma: 2,
    },
    skills: { stealth: 2 },
    senses: "blindsight 30 ft., passive Perception 9",
    traits: [
      {
        name: "Amphibious",
        description: "The crab can breathe air and water.",
      },
    ],
    actions: [
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "bludgeoning", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_crocodile",
    name: "Crocodile",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 12,
    acType: "natural armor",
    hitPoints: 19,
    speed: { walk: 20, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    skills: { stealth: 2 },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Hold Breath",
        description: "The crocodile can hold its breath for 15 minutes.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [10], flatBonus: 2 },
        description: "Target is grappled (escape DC 12) and restrained until the grapple ends.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_deer",
    name: "Deer",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 4,
    speed: { walk: 50 },
    abilities: {
      strength: 11,
      dexterity: 16,
      constitution: 11,
      intelligence: 2,
      wisdom: 14,
      charisma: 5,
    },
    senses: "passive Perception 12",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [4] },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_dire_wolf",
    name: "Dire Wolf",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 14,
    acType: "natural armor",
    hitPoints: 37,
    speed: { walk: 50 },
    abilities: {
      strength: 17,
      dexterity: 15,
      constitution: 15,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Hearing and Smell",
        description:
          "The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The wolf has advantage on an attack roll against a creature if at least one of the wolf's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 3 },
        description:
          "If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_draft_horse",
    name: "Draft Horse",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 19,
    speed: { walk: 40 },
    abilities: {
      strength: 18,
      dexterity: 10,
      constitution: 12,
      intelligence: 2,
      wisdom: 11,
      charisma: 7,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4], flatBonus: 4 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_eagle",
    name: "Eagle",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 6,
      dexterity: 15,
      constitution: 10,
      intelligence: 2,
      wisdom: 14,
      charisma: 7,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    traits: [
      {
        name: "Keen Sight",
        description: "The eagle has advantage on Wisdom (Perception) checks that rely on sight.",
      },
    ],
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_elephant",
    name: "Elephant",
    size: "huge",
    cr: 4,
    xp: 1100,
    ac: 12,
    acType: "natural armor",
    hitPoints: 76,
    speed: { walk: 40 },
    abilities: {
      strength: 22,
      dexterity: 9,
      constitution: 17,
      intelligence: 3,
      wisdom: 11,
      charisma: 6,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Trampling Charge",
        description:
          "If the elephant moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the elephant can make one stomp attack against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 8,
        reach: 5,
        damage: { type: "piercing", dice: [8, 8, 8], flatBonus: 6 },
      },
      {
        name: "Stomp",
        attackType: "melee",
        attackBonus: 8,
        reach: 5,
        damage: { type: "bludgeoning", dice: [10, 10, 10], flatBonus: 6 },
        description: "Can only target prone creatures.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_elk",
    name: "Elk",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 13,
    speed: { walk: 50 },
    abilities: {
      strength: 16,
      dexterity: 10,
      constitution: 12,
      intelligence: 2,
      wisdom: 10,
      charisma: 6,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Charge",
        description:
          "If the elk moves at least 20 feet straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 7 (2d6) damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 3 },
      },
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4], flatBonus: 3 },
        description: "Can only target prone creatures.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_flying_snake",
    name: "Flying Snake",
    size: "tiny",
    cr: 0.125,
    xp: 25,
    ac: 14,
    hitPoints: 5,
    speed: { walk: 30, fly: 60, swim: 30 },
    abilities: {
      strength: 4,
      dexterity: 18,
      constitution: 11,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    senses: "blindsight 10 ft., passive Perception 11",
    traits: [
      {
        name: "Flyby",
        description:
          "The snake doesn't provoke opportunity attacks when it flies out of an enemy's reach.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description: "Plus 7 (3d4) poison damage.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_frog",
    name: "Frog",
    size: "tiny",
    cr: 0,
    xp: 0,
    ac: 11,
    hitPoints: 1,
    speed: { walk: 20, swim: 20 },
    abilities: {
      strength: 1,
      dexterity: 13,
      constitution: 8,
      intelligence: 1,
      wisdom: 8,
      charisma: 3,
    },
    skills: { perception: 1, stealth: 3 },
    senses: "darkvision 30 ft., passive Perception 11",
    traits: [
      {
        name: "Amphibious",
        description: "The frog can breathe air and water.",
      },
      {
        name: "Standing Leap",
        description:
          "The frog's long jump is up to 10 feet and its high jump is up to 5 feet, with or without a running start.",
      },
    ],
    actions: [],
    source: "srd51",
  },
  {
    id: "srd51_giant_ape",
    name: "Giant Ape",
    size: "huge",
    cr: 7,
    xp: 2900,
    ac: 12,
    hitPoints: 157,
    speed: { walk: 40, climb: 40 },
    abilities: {
      strength: 23,
      dexterity: 14,
      constitution: 18,
      intelligence: 7,
      wisdom: 12,
      charisma: 7,
    },
    skills: { athletics: 9, perception: 4 },
    senses: "passive Perception 14",
    actions: [
      {
        name: "Fist",
        attackType: "melee",
        attackBonus: 9,
        reach: 10,
        damage: { type: "bludgeoning", dice: [10, 10, 10], flatBonus: 6 },
      },
      {
        name: "Rock",
        attackType: "ranged",
        attackBonus: 9,
        range: { normal: 50, long: 100 },
        damage: { type: "bludgeoning", dice: [6, 6, 6, 6, 6, 6, 6], flatBonus: 6 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_badger",
    name: "Giant Badger",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 13,
    speed: { walk: 30, burrow: 10 },
    abilities: {
      strength: 13,
      dexterity: 10,
      constitution: 15,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    senses: "darkvision 30 ft., passive Perception 11",
    traits: [
      {
        name: "Keen Smell",
        description: "The badger has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 1 },
      },
      {
        name: "Claws",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "slashing", dice: [4, 4], flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_bat",
    name: "Giant Bat",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 22,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 15,
      dexterity: 16,
      constitution: 11,
      intelligence: 2,
      wisdom: 12,
      charisma: 6,
    },
    senses: "blindsight 60 ft., passive Perception 11",
    traits: [
      {
        name: "Echolocation",
        description: "The bat can't use its blindsight while deafened.",
      },
      {
        name: "Keen Hearing",
        description: "The bat has advantage on Wisdom (Perception) checks that rely on hearing.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_boar",
    name: "Giant Boar",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 12,
    acType: "natural armor",
    hitPoints: 42,
    speed: { walk: 40 },
    abilities: {
      strength: 17,
      dexterity: 10,
      constitution: 16,
      intelligence: 2,
      wisdom: 7,
      charisma: 5,
    },
    senses: "passive Perception 8",
    traits: [
      {
        name: "Charge",
        description:
          "If the boar moves at least 20 feet straight toward a target and then hits it with a tusk attack on the same turn, the target takes an extra 7 (2d6) slashing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
      },
      {
        name: "Relentless",
        description:
          "If the boar takes 10 damage or less that would reduce it to 0 hit points, it is reduced to 1 hit point instead. Recharges after a short or long rest.",
      },
    ],
    actions: [
      {
        name: "Tusk",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_centipede",
    name: "Giant Centipede",
    size: "small",
    cr: 0.25,
    xp: 50,
    ac: 13,
    acType: "natural armor",
    hitPoints: 4,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 5,
      dexterity: 14,
      constitution: 12,
      intelligence: 1,
      wisdom: 7,
      charisma: 3,
    },
    senses: "blindsight 30 ft., passive Perception 8",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 2 },
        description:
          "Target must succeed on a DC 11 Constitution saving throw or take 10 (3d6) poison damage. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, and paralyzed while poisoned.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_constrictor_snake",
    name: "Giant Constrictor Snake",
    size: "huge",
    cr: 2,
    xp: 450,
    ac: 12,
    hitPoints: 60,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 19,
      dexterity: 14,
      constitution: 12,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    skills: { perception: 2 },
    senses: "blindsight 10 ft., passive Perception 12",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 4 },
      },
      {
        name: "Constrict",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "bludgeoning", dice: [8, 8], flatBonus: 4 },
        description: "Target is grappled (escape DC 16) and restrained until the grapple ends.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_crab",
    name: "Giant Crab",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 15,
    acType: "natural armor",
    hitPoints: 13,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 13,
      dexterity: 15,
      constitution: 11,
      intelligence: 1,
      wisdom: 9,
      charisma: 3,
    },
    skills: { stealth: 4 },
    senses: "blindsight 30 ft., passive Perception 9",
    traits: [
      {
        name: "Amphibious",
        description: "The crab can breathe air and water.",
      },
    ],
    actions: [
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 1 },
        description:
          "Target is grappled (escape DC 11). The crab has two claws, each of which can grapple only one target.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_crocodile",
    name: "Giant Crocodile",
    size: "huge",
    cr: 5,
    xp: 1800,
    ac: 14,
    acType: "natural armor",
    hitPoints: 85,
    speed: { walk: 30, swim: 50 },
    abilities: {
      strength: 21,
      dexterity: 9,
      constitution: 17,
      intelligence: 2,
      wisdom: 10,
      charisma: 7,
    },
    skills: { stealth: 5 },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Hold Breath",
        description: "The crocodile can hold its breath for 30 minutes.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 8,
        reach: 5,
        damage: { type: "piercing", dice: [10, 10, 10], flatBonus: 5 },
        description: "Target is grappled (escape DC 16) and restrained until the grapple ends.",
      },
      {
        name: "Tail",
        attackType: "melee",
        attackBonus: 8,
        reach: 10,
        damage: { type: "bludgeoning", dice: [8, 8], flatBonus: 5 },
        description:
          "If the target is a creature, it must succeed on a DC 16 Strength saving throw or be knocked prone.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_eagle",
    name: "Giant Eagle",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 13,
    hitPoints: 26,
    speed: { walk: 10, fly: 80 },
    abilities: {
      strength: 16,
      dexterity: 17,
      constitution: 13,
      intelligence: 8,
      wisdom: 14,
      charisma: 10,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    traits: [
      {
        name: "Keen Sight",
        description: "The eagle has advantage on Wisdom (Perception) checks that rely on sight.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 3 },
      },
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_elk",
    name: "Giant Elk",
    size: "huge",
    cr: 2,
    xp: 450,
    ac: 14,
    acType: "natural armor",
    hitPoints: 42,
    speed: { walk: 60 },
    abilities: {
      strength: 19,
      dexterity: 16,
      constitution: 14,
      intelligence: 7,
      wisdom: 14,
      charisma: 10,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    traits: [
      {
        name: "Charge",
        description:
          "If the elk moves at least 20 feet straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 7 (2d6) damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be knocked prone.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "bludgeoning", dice: [6, 6], flatBonus: 4 },
      },
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "bludgeoning", dice: [8, 8, 8, 8], flatBonus: 4 },
        description: "Can only target prone creatures.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_fire_beetle",
    name: "Giant Fire Beetle",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 13,
    acType: "natural armor",
    hitPoints: 4,
    speed: { walk: 30 },
    abilities: {
      strength: 8,
      dexterity: 10,
      constitution: 12,
      intelligence: 1,
      wisdom: 7,
      charisma: 3,
    },
    senses: "blindsight 30 ft., passive Perception 8",
    traits: [
      {
        name: "Illumination",
        description:
          "The beetle sheds bright light in a 10-foot radius and dim light for an additional 10 feet.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 1,
        reach: 5,
        damage: { type: "slashing", dice: [6], flatBonus: -1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_frog",
    name: "Giant Frog",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 11,
    hitPoints: 18,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 12,
      dexterity: 13,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    skills: { perception: 2, stealth: 3 },
    senses: "darkvision 30 ft., passive Perception 12",
    traits: [
      {
        name: "Amphibious",
        description: "The frog can breathe air and water.",
      },
      {
        name: "Standing Leap",
        description:
          "The frog's long jump is up to 20 feet and its high jump is up to 10 feet, with or without a running start.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 1 },
        description: "Target is grappled (escape DC 11) and restrained until the grapple ends.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_goat",
    name: "Giant Goat",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 11,
    acType: "natural armor",
    hitPoints: 19,
    speed: { walk: 40 },
    abilities: {
      strength: 17,
      dexterity: 11,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 6,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Charge",
        description:
          "If the goat moves at least 20 feet straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 5 (2d4) bludgeoning damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.",
      },
      {
        name: "Sure-Footed",
        description:
          "The goat has advantage on Strength and Dexterity saving throws made against effects that would knock it prone.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_hyena",
    name: "Giant Hyena",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 12,
    hitPoints: 45,
    speed: { walk: 50 },
    abilities: {
      strength: 16,
      dexterity: 14,
      constitution: 14,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Rampage",
        description:
          "When the hyena reduces a creature to 0 hit points with a melee attack on its turn, the hyena can take a bonus action to move up to half its speed and make a bite attack.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_lizard",
    name: "Giant Lizard",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 12,
    acType: "natural armor",
    hitPoints: 19,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 15,
      dexterity: 12,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    senses: "darkvision 30 ft., passive Perception 10",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_octopus",
    name: "Giant Octopus",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 11,
    hitPoints: 52,
    speed: { walk: 10, swim: 60 },
    abilities: {
      strength: 17,
      dexterity: 13,
      constitution: 13,
      intelligence: 4,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 4, stealth: 5 },
    senses: "darkvision 60 ft., passive Perception 14",
    traits: [
      {
        name: "Hold Breath",
        description: "While out of water, the octopus can hold its breath for 1 hour.",
      },
      {
        name: "Underwater Camouflage",
        description:
          "The octopus has advantage on Dexterity (Stealth) checks made while underwater.",
      },
      {
        name: "Water Breathing",
        description: "The octopus can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Tentacles",
        attackType: "melee",
        attackBonus: 5,
        reach: 15,
        damage: { type: "bludgeoning", dice: [6, 6], flatBonus: 3 },
        description: "Target is grappled (escape DC 16) and restrained until the grapple ends.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_owl",
    name: "Giant Owl",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 12,
    hitPoints: 19,
    speed: { walk: 5, fly: 60 },
    abilities: {
      strength: 13,
      dexterity: 15,
      constitution: 12,
      intelligence: 8,
      wisdom: 13,
      charisma: 10,
    },
    skills: { perception: 5, stealth: 4 },
    senses: "darkvision 120 ft., passive Perception 15",
    traits: [
      {
        name: "Flyby",
        description:
          "The owl doesn't provoke opportunity attacks when it flies out of an enemy's reach.",
      },
      {
        name: "Keen Hearing and Sight",
        description:
          "The owl has advantage on Wisdom (Perception) checks that rely on hearing or sight.",
      },
    ],
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_poisonous_snake",
    name: "Giant Poisonous Snake",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 14,
    hitPoints: 11,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 10,
      dexterity: 18,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    skills: { perception: 2 },
    senses: "blindsight 10 ft., passive Perception 12",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "piercing", dice: [4], flatBonus: 4 },
        description:
          "Target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much on a successful one.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_rat",
    name: "Giant Rat",
    size: "small",
    cr: 0.125,
    xp: 25,
    ac: 12,
    hitPoints: 7,
    speed: { walk: 30 },
    abilities: {
      strength: 7,
      dexterity: 15,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 4,
    },
    senses: "darkvision 60 ft., passive Perception 10",
    traits: [
      {
        name: "Keen Smell",
        description: "The rat has advantage on Wisdom (Perception) checks that rely on smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The rat has advantage on an attack roll against a creature if at least one of the rat's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_scorpion",
    name: "Giant Scorpion",
    size: "large",
    cr: 3,
    xp: 700,
    ac: 15,
    acType: "natural armor",
    hitPoints: 52,
    speed: { walk: 40 },
    abilities: {
      strength: 15,
      dexterity: 13,
      constitution: 15,
      intelligence: 1,
      wisdom: 9,
      charisma: 3,
    },
    senses: "blindsight 60 ft., passive Perception 9",
    actions: [
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [8], flatBonus: 2 },
        description:
          "Target is grappled (escape DC 12). The scorpion has two claws, each of which can grapple only one target.",
      },
      {
        name: "Sting",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [10], flatBonus: 2 },
        description:
          "Target must make a DC 12 Constitution saving throw, taking 22 (4d10) poison damage on a failed save, or half as much on a successful one.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_sea_horse",
    name: "Giant Sea Horse",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 13,
    acType: "natural armor",
    hitPoints: 16,
    speed: { swim: 40 },
    abilities: {
      strength: 12,
      dexterity: 15,
      constitution: 11,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Charge",
        description:
          "If the sea horse moves at least 20 feet straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 7 (2d6) bludgeoning damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.",
      },
      {
        name: "Water Breathing",
        description: "The sea horse can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_shark",
    name: "Giant Shark",
    size: "huge",
    cr: 5,
    xp: 1800,
    ac: 13,
    acType: "natural armor",
    hitPoints: 126,
    speed: { swim: 50 },
    abilities: {
      strength: 23,
      dexterity: 11,
      constitution: 21,
      intelligence: 1,
      wisdom: 10,
      charisma: 5,
    },
    skills: { perception: 3 },
    senses: "blindsight 60 ft., passive Perception 13",
    traits: [
      {
        name: "Blood Frenzy",
        description:
          "The shark has advantage on melee attack rolls against any creature that doesn't have all its hit points.",
      },
      {
        name: "Water Breathing",
        description: "The shark can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 9,
        reach: 5,
        damage: { type: "piercing", dice: [10, 10, 10], flatBonus: 6 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_spider",
    name: "Giant Spider",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 14,
    acType: "natural armor",
    hitPoints: 26,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 14,
      dexterity: 16,
      constitution: 12,
      intelligence: 2,
      wisdom: 11,
      charisma: 4,
    },
    skills: { stealth: 7 },
    senses: "blindsight 10 ft., darkvision 60 ft., passive Perception 10",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.",
      },
      {
        name: "Web Sense",
        description:
          "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.",
      },
      {
        name: "Web Walker",
        description: "The spider ignores movement restrictions caused by webbing.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 3 },
        description:
          "Target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, and paralyzed while poisoned.",
      },
      {
        name: "Web",
        attackType: "ranged",
        attackBonus: 5,
        range: { normal: 30, long: 60 },
        damage: { type: "bludgeoning" },
        description:
          "Target is restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, bursting the webbing on a success. Recharge 5-6.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_toad",
    name: "Giant Toad",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 11,
    hitPoints: 39,
    speed: { walk: 20, swim: 40 },
    abilities: {
      strength: 15,
      dexterity: 13,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    senses: "darkvision 30 ft., passive Perception 10",
    traits: [
      {
        name: "Amphibious",
        description: "The toad can breathe air and water.",
      },
      {
        name: "Standing Leap",
        description:
          "The toad's long jump is up to 20 feet and its high jump is up to 10 feet, with or without a running start.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [10], flatBonus: 2 },
        description:
          "Plus 5 (1d10) poison damage. Target is grappled (escape DC 13) and restrained until the grapple ends.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_vulture",
    name: "Giant Vulture",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 10,
    hitPoints: 22,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 15,
      dexterity: 10,
      constitution: 15,
      intelligence: 6,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Sight and Smell",
        description:
          "The vulture has advantage on Wisdom (Perception) checks that rely on sight or smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The vulture has advantage on an attack roll against a creature if at least one of the vulture's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4], flatBonus: 2 },
      },
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_wasp",
    name: "Giant Wasp",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 12,
    hitPoints: 13,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 10,
      dexterity: 14,
      constitution: 10,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Sting",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
        description:
          "Target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, and paralyzed while poisoned.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_weasel",
    name: "Giant Weasel",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 13,
    hitPoints: 9,
    speed: { walk: 40 },
    abilities: {
      strength: 11,
      dexterity: 16,
      constitution: 10,
      intelligence: 4,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3, stealth: 5 },
    senses: "darkvision 60 ft., passive Perception 13",
    traits: [
      {
        name: "Keen Hearing and Smell",
        description:
          "The weasel has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_giant_wolf_spider",
    name: "Giant Wolf Spider",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 11,
    speed: { walk: 40, climb: 40 },
    abilities: {
      strength: 12,
      dexterity: 16,
      constitution: 13,
      intelligence: 3,
      wisdom: 12,
      charisma: 4,
    },
    skills: { perception: 3, stealth: 7 },
    senses: "blindsight 10 ft., darkvision 60 ft., passive Perception 13",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.",
      },
      {
        name: "Web Sense",
        description:
          "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.",
      },
      {
        name: "Web Walker",
        description: "The spider ignores movement restrictions caused by webbing.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 1 },
        description:
          "Target must make a DC 11 Constitution saving throw, taking 7 (2d6) poison damage on a failed save, or half as much on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, and paralyzed while poisoned.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_goat",
    name: "Goat",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 4,
    speed: { walk: 40 },
    abilities: {
      strength: 12,
      dexterity: 10,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Charge",
        description:
          "If the goat moves at least 20 feet straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 2 (1d4) bludgeoning damage. If the target is a creature, it must succeed on a DC 10 Strength saving throw or be knocked prone.",
      },
      {
        name: "Sure-Footed",
        description:
          "The goat has advantage on Strength and Dexterity saving throws made against effects that would knock it prone.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_hawk",
    name: "Hawk",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 1,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 5,
      dexterity: 16,
      constitution: 8,
      intelligence: 2,
      wisdom: 14,
      charisma: 6,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    traits: [
      {
        name: "Keen Sight",
        description: "The hawk has advantage on Wisdom (Perception) checks that rely on sight.",
      },
    ],
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_hunter_shark",
    name: "Hunter Shark",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 12,
    acType: "natural armor",
    hitPoints: 45,
    speed: { swim: 40 },
    abilities: {
      strength: 18,
      dexterity: 13,
      constitution: 15,
      intelligence: 1,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2 },
    senses: "blindsight 30 ft., passive Perception 12",
    traits: [
      {
        name: "Blood Frenzy",
        description:
          "The shark has advantage on melee attack rolls against any creature that doesn't have all its hit points.",
      },
      {
        name: "Water Breathing",
        description: "The shark can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [8, 8], flatBonus: 4 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_hyena",
    name: "Hyena",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 5,
    speed: { walk: 50 },
    abilities: {
      strength: 11,
      dexterity: 13,
      constitution: 12,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The hyena has advantage on an attack roll against a creature if at least one of the hyena's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [6] },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_jackal",
    name: "Jackal",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 40 },
    abilities: {
      strength: 8,
      dexterity: 15,
      constitution: 11,
      intelligence: 3,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Hearing and Smell",
        description:
          "The jackal has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The jackal has advantage on an attack roll against a creature if at least one of the jackal's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 1,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: -1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_killer_whale",
    name: "Killer Whale",
    size: "huge",
    cr: 3,
    xp: 700,
    ac: 12,
    acType: "natural armor",
    hitPoints: 90,
    speed: { swim: 60 },
    abilities: {
      strength: 19,
      dexterity: 10,
      constitution: 13,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "blindsight 120 ft., passive Perception 13",
    traits: [
      {
        name: "Echolocation",
        description: "The whale can't use its blindsight while deafened.",
      },
      {
        name: "Hold Breath",
        description: "The whale can hold its breath for 30 minutes.",
      },
      {
        name: "Keen Hearing",
        description: "The whale has advantage on Wisdom (Perception) checks that rely on hearing.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6, 6, 6, 6], flatBonus: 4 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_lion",
    name: "Lion",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 12,
    hitPoints: 26,
    speed: { walk: 50 },
    abilities: {
      strength: 17,
      dexterity: 15,
      constitution: 13,
      intelligence: 3,
      wisdom: 12,
      charisma: 8,
    },
    skills: { perception: 3, stealth: 6 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The lion has advantage on Wisdom (Perception) checks that rely on smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The lion has advantage on an attack roll against a creature if at least one of the lion's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
      {
        name: "Pounce",
        description:
          "If the lion moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the lion can make one bite attack against it as a bonus action.",
      },
      {
        name: "Running Leap",
        description: "With a 10-foot running start, the lion can long jump up to 25 feet.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 3 },
      },
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [6], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_lizard",
    name: "Lizard",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 2,
    speed: { walk: 20, climb: 20 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 10,
      intelligence: 1,
      wisdom: 8,
      charisma: 3,
    },
    senses: "darkvision 30 ft., passive Perception 9",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_mammoth",
    name: "Mammoth",
    size: "huge",
    cr: 6,
    xp: 2300,
    ac: 13,
    acType: "natural armor",
    hitPoints: 126,
    speed: { walk: 40 },
    abilities: {
      strength: 24,
      dexterity: 9,
      constitution: 21,
      intelligence: 3,
      wisdom: 11,
      charisma: 6,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Trampling Charge",
        description:
          "If the mammoth moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 18 Strength saving throw or be knocked prone. If the target is prone, the mammoth can make one stomp attack against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 10,
        reach: 10,
        damage: { type: "piercing", dice: [8, 8, 8, 8], flatBonus: 7 },
      },
      {
        name: "Stomp",
        attackType: "melee",
        attackBonus: 10,
        reach: 5,
        damage: { type: "bludgeoning", dice: [10, 10, 10, 10], flatBonus: 7 },
        description: "Can only target prone creatures.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_mastiff",
    name: "Mastiff",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 12,
    hitPoints: 5,
    speed: { walk: 40 },
    abilities: {
      strength: 13,
      dexterity: 14,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Hearing and Smell",
        description:
          "The mastiff has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 1 },
        description:
          "If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_mule",
    name: "Mule",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 10,
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 14,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Beast of Burden",
        description:
          "The mule is considered to be a Large animal for the purpose of determining its carrying capacity.",
      },
      {
        name: "Sure-Footed",
        description:
          "The mule has advantage on Strength and Dexterity saving throws made against effects that would knock it prone.",
      },
    ],
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_octopus",
    name: "Octopus",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 5, swim: 30 },
    abilities: {
      strength: 4,
      dexterity: 15,
      constitution: 11,
      intelligence: 3,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2, stealth: 4 },
    senses: "darkvision 30 ft., passive Perception 12",
    traits: [
      {
        name: "Hold Breath",
        description: "While out of water, the octopus can hold its breath for 30 minutes.",
      },
      {
        name: "Underwater Camouflage",
        description:
          "The octopus has advantage on Dexterity (Stealth) checks made while underwater.",
      },
      {
        name: "Water Breathing",
        description: "The octopus can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Tentacles",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", flatBonus: 1 },
        description: "Target is grappled (escape DC 10).",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_owl",
    name: "Owl",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 1,
    speed: { walk: 5, fly: 60 },
    abilities: {
      strength: 3,
      dexterity: 13,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3, stealth: 3 },
    senses: "darkvision 120 ft., passive Perception 13",
    traits: [
      {
        name: "Flyby",
        description:
          "The owl doesn't provoke opportunity attacks when it flies out of an enemy's reach.",
      },
      {
        name: "Keen Hearing and Sight",
        description:
          "The owl has advantage on Wisdom (Perception) checks that rely on hearing or sight.",
      },
    ],
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "slashing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_panther",
    name: "Panther",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 12,
    hitPoints: 13,
    speed: { walk: 50, climb: 40 },
    abilities: {
      strength: 14,
      dexterity: 15,
      constitution: 10,
      intelligence: 3,
      wisdom: 14,
      charisma: 7,
    },
    skills: { perception: 4, stealth: 6 },
    senses: "passive Perception 14",
    traits: [
      {
        name: "Keen Smell",
        description: "The panther has advantage on Wisdom (Perception) checks that rely on smell.",
      },
      {
        name: "Pounce",
        description:
          "If the panther moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the panther can make one bite attack against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
      },
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_plesiosaurus",
    name: "Plesiosaurus",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 13,
    acType: "natural armor",
    hitPoints: 68,
    speed: { walk: 20, swim: 40 },
    abilities: {
      strength: 18,
      dexterity: 15,
      constitution: 16,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Hold Breath",
        description: "The plesiosaurus can hold its breath for 1 hour.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "piercing", dice: [6, 6, 6], flatBonus: 4 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_poisonous_snake",
    name: "Poisonous Snake",
    size: "tiny",
    cr: 0.125,
    xp: 25,
    ac: 13,
    hitPoints: 2,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 2,
      dexterity: 16,
      constitution: 11,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    senses: "blindsight 10 ft., passive Perception 10",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description:
          "Target must make a DC 10 Constitution saving throw, taking 5 (2d4) poison damage on a failed save, or half as much on a successful one.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_polar_bear",
    name: "Polar Bear",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 12,
    acType: "natural armor",
    hitPoints: 42,
    speed: { walk: 40, swim: 30 },
    abilities: {
      strength: 20,
      dexterity: 10,
      constitution: 16,
      intelligence: 2,
      wisdom: 13,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The bear has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 7,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 5 },
      },
      {
        name: "Claws",
        attackType: "melee",
        attackBonus: 7,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 5 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_pony",
    name: "Pony",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 10,
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 15,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 11,
      charisma: 7,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_quipper",
    name: "Quipper",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 1,
    speed: { swim: 40 },
    abilities: {
      strength: 2,
      dexterity: 16,
      constitution: 9,
      intelligence: 1,
      wisdom: 7,
      charisma: 2,
    },
    senses: "darkvision 60 ft., passive Perception 8",
    traits: [
      {
        name: "Blood Frenzy",
        description:
          "The quipper has advantage on melee attack rolls against any creature that doesn't have all its hit points.",
      },
      {
        name: "Water Breathing",
        description: "The quipper can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_rat",
    name: "Rat",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 1,
    speed: { walk: 20 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 9,
      intelligence: 2,
      wisdom: 10,
      charisma: 4,
    },
    senses: "darkvision 30 ft., passive Perception 10",
    traits: [
      {
        name: "Keen Smell",
        description: "The rat has advantage on Wisdom (Perception) checks that rely on smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_raven",
    name: "Raven",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 1,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 2,
      dexterity: 14,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Mimicry",
        description:
          "The raven can mimic simple sounds it has heard. A creature that hears the sounds can tell they are imitations with a successful DC 10 Wisdom (Insight) check.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_reef_shark",
    name: "Reef Shark",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 12,
    acType: "natural armor",
    hitPoints: 22,
    speed: { swim: 40 },
    abilities: {
      strength: 14,
      dexterity: 13,
      constitution: 13,
      intelligence: 1,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2 },
    senses: "blindsight 30 ft., passive Perception 12",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The shark has advantage on an attack roll against a creature if at least one of the shark's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
      {
        name: "Water Breathing",
        description: "The shark can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 2 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_rhinoceros",
    name: "Rhinoceros",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 11,
    acType: "natural armor",
    hitPoints: 45,
    speed: { walk: 40 },
    abilities: {
      strength: 21,
      dexterity: 8,
      constitution: 15,
      intelligence: 2,
      wisdom: 12,
      charisma: 6,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Charge",
        description:
          "If the rhinoceros moves at least 20 feet straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) bludgeoning damage. If the target is a creature, it must succeed on a DC 15 Strength saving throw or be knocked prone.",
      },
    ],
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 7,
        reach: 5,
        damage: { type: "bludgeoning", dice: [8, 8], flatBonus: 5 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_riding_horse",
    name: "Riding Horse",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 13,
    speed: { walk: 60 },
    abilities: {
      strength: 16,
      dexterity: 10,
      constitution: 12,
      intelligence: 2,
      wisdom: 11,
      charisma: 7,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_saber_toothed_tiger",
    name: "Saber-Toothed Tiger",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 12,
    hitPoints: 52,
    speed: { walk: 40 },
    abilities: {
      strength: 18,
      dexterity: 14,
      constitution: 15,
      intelligence: 3,
      wisdom: 12,
      charisma: 8,
    },
    skills: { perception: 3, stealth: 6 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The tiger has advantage on Wisdom (Perception) checks that rely on smell.",
      },
      {
        name: "Pounce",
        description:
          "If the tiger moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [10], flatBonus: 5 },
      },
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 5 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_scorpion",
    name: "Scorpion",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    acType: "natural armor",
    hitPoints: 1,
    speed: { walk: 10 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 8,
      intelligence: 1,
      wisdom: 8,
      charisma: 2,
    },
    senses: "blindsight 10 ft., passive Perception 9",
    actions: [
      {
        name: "Sting",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description:
          "Target must make a DC 9 Constitution saving throw, taking 4 (1d8) poison damage on a failed save, or half as much on a successful one.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_sea_horse",
    name: "Sea Horse",
    size: "tiny",
    cr: 0,
    xp: 0,
    ac: 11,
    hitPoints: 1,
    speed: { swim: 20 },
    abilities: {
      strength: 1,
      dexterity: 12,
      constitution: 8,
      intelligence: 1,
      wisdom: 10,
      charisma: 2,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Water Breathing",
        description: "The sea horse can breathe only underwater.",
      },
    ],
    actions: [],
    source: "srd51",
  },
  {
    id: "srd51_spider",
    name: "Spider",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 1,
    speed: { walk: 20, climb: 20 },
    abilities: {
      strength: 2,
      dexterity: 14,
      constitution: 8,
      intelligence: 1,
      wisdom: 10,
      charisma: 2,
    },
    skills: { stealth: 4 },
    senses: "darkvision 30 ft., passive Perception 10",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.",
      },
      {
        name: "Web Sense",
        description:
          "While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.",
      },
      {
        name: "Web Walker",
        description: "The spider ignores movement restrictions caused by webbing.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description:
          "Target must succeed on a DC 9 Constitution saving throw or take 2 (1d4) poison damage.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_stirge",
    name: "Stirge",
    size: "tiny",
    cr: 0.125,
    xp: 25,
    ac: 14,
    acType: "natural armor",
    hitPoints: 2,
    speed: { walk: 10, fly: 40 },
    abilities: {
      strength: 4,
      dexterity: 16,
      constitution: 11,
      intelligence: 2,
      wisdom: 8,
      charisma: 6,
    },
    senses: "darkvision 60 ft., passive Perception 9",
    actions: [
      {
        name: "Blood Drain",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 3 },
        description:
          "The stirge attaches to the target. While attached, the stirge doesn't attack. Instead, at the start of each of the stirge's turns, the target loses 5 (1d4 + 3) hit points due to blood loss. The stirge can detach itself by spending 5 feet of its movement. It does so after it drains 10 hit points of blood from the target or the target dies.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_tiger",
    name: "Tiger",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 12,
    hitPoints: 37,
    speed: { walk: 40 },
    abilities: {
      strength: 17,
      dexterity: 15,
      constitution: 14,
      intelligence: 3,
      wisdom: 12,
      charisma: 8,
    },
    skills: { perception: 3, stealth: 6 },
    senses: "darkvision 60 ft., passive Perception 13",
    traits: [
      {
        name: "Keen Smell",
        description: "The tiger has advantage on Wisdom (Perception) checks that rely on smell.",
      },
      {
        name: "Pounce",
        description:
          "If the tiger moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [10], flatBonus: 3 },
      },
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [8], flatBonus: 3 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_triceratops",
    name: "Triceratops",
    size: "huge",
    cr: 5,
    xp: 1800,
    ac: 13,
    acType: "natural armor",
    hitPoints: 95,
    speed: { walk: 50 },
    abilities: {
      strength: 22,
      dexterity: 9,
      constitution: 17,
      intelligence: 2,
      wisdom: 11,
      charisma: 5,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Trampling Charge",
        description:
          "If the triceratops moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the triceratops can make one stomp attack against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 9,
        reach: 5,
        damage: { type: "piercing", dice: [8, 8, 8, 8], flatBonus: 6 },
      },
      {
        name: "Stomp",
        attackType: "melee",
        attackBonus: 9,
        reach: 5,
        damage: { type: "bludgeoning", dice: [10, 10, 10], flatBonus: 6 },
        description: "Can only target prone creatures.",
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_tyrannosaurus_rex",
    name: "Tyrannosaurus Rex",
    size: "huge",
    cr: 8,
    xp: 3900,
    ac: 13,
    acType: "natural armor",
    hitPoints: 136,
    speed: { walk: 50 },
    abilities: {
      strength: 25,
      dexterity: 10,
      constitution: 19,
      intelligence: 2,
      wisdom: 12,
      charisma: 9,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 10,
        reach: 10,
        damage: { type: "piercing", dice: [12, 12, 12, 12], flatBonus: 7 },
        description:
          "If the target is a Medium or smaller creature, it is grappled (escape DC 17). Until this grapple ends, the target is restrained, and the tyrannosaurus can't bite another target.",
      },
      {
        name: "Tail",
        attackType: "melee",
        attackBonus: 10,
        reach: 10,
        damage: { type: "bludgeoning", dice: [8, 8, 8], flatBonus: 7 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_vulture",
    name: "Vulture",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 5,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 7,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 12,
      charisma: 4,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Sight and Smell",
        description:
          "The vulture has advantage on Wisdom (Perception) checks that rely on sight or smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The vulture has advantage on an attack roll against a creature if at least one of the vulture's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [4] },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_warhorse",
    name: "Warhorse",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 11,
    hitPoints: 19,
    speed: { walk: 60 },
    abilities: {
      strength: 18,
      dexterity: 12,
      constitution: 13,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Trampling Charge",
        description:
          "If the horse moves at least 20 feet straight toward a creature and then hits it with a hooves attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the horse can make another attack with its hooves against it as a bonus action.",
      },
    ],
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6, 6], flatBonus: 4 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_weasel",
    name: "Weasel",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 1,
    speed: { walk: 30 },
    abilities: {
      strength: 3,
      dexterity: 16,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 3,
    },
    skills: { perception: 3, stealth: 5 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Hearing and Smell",
        description:
          "The weasel has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd51",
  },
  {
    id: "srd51_wolf",
    name: "Wolf",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 13,
    acType: "natural armor",
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 12,
      dexterity: 15,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Keen Hearing and Smell",
        description:
          "The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.",
      },
      {
        name: "Pack Tactics",
        description:
          "The wolf has advantage on attack rolls against a creature if at least one of the wolf's allies is within 5 feet of the creature and the ally isn't incapacitated.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4], flatBonus: 2 },
        description:
          "If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.",
      },
    ],
    source: "srd51",
  },
]
