import type { Beast } from "../beasts"

export const srd52Beasts: Beast[] = [
  {
    id: "srd52_allosaurus",
    name: "Allosaurus",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 13,
    hitPoints: 51,
    speed: { walk: 60 },
    abilities: {
      strength: 19,
      dexterity: 13,
      constitution: 17,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 5 },
    senses: "passive Perception 15",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [10, 10], flatBonus: 4 },
      },
      {
        name: "Claws",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "slashing", dice: [8], flatBonus: 4 },
        description:
          "If the target is a Large or smaller creature and the allosaurus moved 30+ feet straight toward it immediately before the hit, the target has the Prone condition, and the allosaurus can make one Bite attack against it.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_ankylosaurus",
    name: "Ankylosaurus",
    size: "huge",
    cr: 3,
    xp: 700,
    ac: 15,
    hitPoints: 68,
    speed: { walk: 30 },
    abilities: {
      strength: 19,
      dexterity: 11,
      constitution: 15,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    senses: "passive Perception 11",
    actions: [
      {
        name: "Tail",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "bludgeoning", dice: [10], flatBonus: 4 },
        description: "If the target is a Huge or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_ape",
    name: "Ape",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 12,
    hitPoints: 19,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 16,
      dexterity: 14,
      constitution: 14,
      intelligence: 6,
      wisdom: 12,
      charisma: 7,
    },
    skills: { athletics: 5, perception: 3 },
    senses: "passive Perception 13",
    actions: [
      {
        name: "Fist",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 3 },
      },
      {
        name: "Rock",
        attackType: "ranged",
        attackBonus: 5,
        range: { normal: 25, long: 50 },
        damage: { type: "bludgeoning", dice: [6, 6], flatBonus: 3 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_archelon",
    name: "Archelon",
    size: "huge",
    cr: 4,
    xp: 1100,
    ac: 17,
    hitPoints: 90,
    speed: { walk: 20, swim: 80 },
    abilities: {
      strength: 18,
      dexterity: 16,
      constitution: 13,
      intelligence: 4,
      wisdom: 14,
      charisma: 6,
    },
    skills: { stealth: 5 },
    senses: "passive Perception 12",
    traits: [
      {
        name: "Amphibious",
        description: "The archelon can breathe air and water.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6, 6], flatBonus: 4 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_baboon",
    name: "Baboon",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 8,
      dexterity: 14,
      constitution: 11,
      intelligence: 4,
      wisdom: 12,
      charisma: 6,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The baboon has Advantage on an attack roll against a creature if at least one of the baboon's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 1,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: -1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_badger",
    name: "Badger",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 5,
    speed: { walk: 20, burrow: 5 },
    abilities: {
      strength: 10,
      dexterity: 11,
      constitution: 16,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3 },
    senses: "Darkvision 30 ft.; passive Perception 13",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_bat",
    name: "Bat",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 1,
    speed: { walk: 5, fly: 30 },
    abilities: {
      strength: 2,
      dexterity: 15,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 4,
    },
    senses: "Blindsight 60 ft.; passive Perception 11",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_black_bear",
    name: "Black Bear",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 11,
    hitPoints: 19,
    speed: { walk: 30, climb: 30, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 12,
      constitution: 14,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 5 },
    senses: "Darkvision 60 ft.; passive Perception 15",
    actions: [
      {
        name: "Rend",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", dice: [6], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_blood_hawk",
    name: "Blood Hawk",
    size: "small",
    cr: 0.125,
    xp: 25,
    ac: 12,
    hitPoints: 7,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 6,
      dexterity: 14,
      constitution: 10,
      intelligence: 3,
      wisdom: 14,
      charisma: 5,
    },
    skills: { perception: 6 },
    senses: "passive Perception 16",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The hawk has Advantage on an attack roll against a creature if at least one of the hawk's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 2 },
        description: "The attack deals 6 (1d8 + 2) Piercing damage if the target is Bloodied.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_boar",
    name: "Boar",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 11,
    hitPoints: 13,
    speed: { walk: 40 },
    abilities: {
      strength: 13,
      dexterity: 11,
      constitution: 14,
      intelligence: 2,
      wisdom: 9,
      charisma: 5,
    },
    senses: "passive Perception 9",
    traits: [
      {
        name: "Bloodied Fury",
        description: "While Bloodied, the boar has Advantage on attack rolls.",
      },
    ],
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 1 },
        description:
          "If the target is a Medium or smaller creature and the boar moved 20+ feet straight toward it immediately before the hit, the target takes an extra 3 (1d6) Piercing damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_brown_bear",
    name: "Brown Bear",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 11,
    hitPoints: 22,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 17,
      dexterity: 12,
      constitution: 15,
      intelligence: 2,
      wisdom: 13,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 3 },
      },
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [4], flatBonus: 3 },
        description: "If the target is a Large or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_camel",
    name: "Camel",
    size: "large",
    cr: 0.125,
    xp: 25,
    ac: 10,
    hitPoints: 17,
    speed: { walk: 50 },
    abilities: {
      strength: 15,
      dexterity: 8,
      constitution: 17,
      intelligence: 2,
      wisdom: 11,
      charisma: 5,
    },
    senses: "Darkvision 60 ft.; passive Perception 10",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_cat",
    name: "Cat",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 2,
    speed: { walk: 40, climb: 40 },
    abilities: {
      strength: 3,
      dexterity: 15,
      constitution: 10,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    traits: [
      {
        name: "Jumper",
        description:
          "The cat's jump distance is determined using its Dexterity rather than its Strength.",
      },
    ],
    actions: [
      {
        name: "Scratch",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_constrictor_snake",
    name: "Constrictor Snake",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 13,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 14,
      constitution: 12,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    skills: { perception: 2, stealth: 4 },
    senses: "Blindsight 10 ft.; passive Perception 12",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 2 },
      },
      {
        name: "Constrict",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4, 4] },
        description:
          "The target has the Grappled condition (escape DC 12). Requires Strength saving throw DC 12 from a Medium or smaller creature.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_crab",
    name: "Crab",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 3,
    speed: { walk: 20, swim: 20 },
    abilities: {
      strength: 6,
      dexterity: 11,
      constitution: 12,
      intelligence: 1,
      wisdom: 8,
      charisma: 2,
    },
    skills: { stealth: 2 },
    senses: "Blindsight 30 ft.; passive Perception 9",
    traits: [
      {
        name: "Amphibious",
        description: "The crab can breathe air and water.",
      },
    ],
    actions: [
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "bludgeoning", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_crocodile",
    name: "Crocodile",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 12,
    hitPoints: 13,
    speed: { walk: 20, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    skills: { stealth: 2 },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Hold Breath",
        description: "The crocodile can hold its breath for 1 hour.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 2 },
        description:
          "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12). While Grappled, the target has the Restrained condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_deer",
    name: "Deer",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 4,
    speed: { walk: 50 },
    abilities: {
      strength: 11,
      dexterity: 16,
      constitution: 11,
      intelligence: 2,
      wisdom: 14,
      charisma: 5,
    },
    skills: { perception: 4 },
    senses: "Darkvision 60 ft.; passive Perception 14",
    traits: [
      {
        name: "Agile",
        description:
          "The deer doesn't provoke an Opportunity Attack when it moves out of an enemy's reach.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4] },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_dire_wolf",
    name: "Dire Wolf",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 14,
    hitPoints: 22,
    speed: { walk: 50 },
    abilities: {
      strength: 17,
      dexterity: 15,
      constitution: 15,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 5, stealth: 4 },
    senses: "Darkvision 60 ft.; passive Perception 15",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The wolf has Advantage on an attack roll against a creature if at least one of the wolf's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [10], flatBonus: 3 },
        description: "If the target is a Large or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_draft_horse",
    name: "Draft Horse",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 15,
    speed: { walk: 40 },
    abilities: {
      strength: 18,
      dexterity: 10,
      constitution: 15,
      intelligence: 2,
      wisdom: 11,
      charisma: 7,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 4 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_eagle",
    name: "Eagle",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 4,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 6,
      dexterity: 15,
      constitution: 12,
      intelligence: 2,
      wisdom: 14,
      charisma: 7,
    },
    skills: { perception: 6 },
    senses: "passive Perception 16",
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "slashing", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_elephant",
    name: "Elephant",
    size: "huge",
    cr: 4,
    xp: 1100,
    ac: 12,
    hitPoints: 76,
    speed: { walk: 40 },
    abilities: {
      strength: 22,
      dexterity: 9,
      constitution: 17,
      intelligence: 3,
      wisdom: 11,
      charisma: 6,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 8,
        reach: 5,
        damage: { type: "piercing", dice: [8, 8], flatBonus: 6 },
        description:
          "If the target is a Huge or smaller creature and the elephant moved 20+ feet straight toward it immediately before the hit, the target has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_elk",
    name: "Elk",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 11,
    speed: { walk: 50 },
    abilities: {
      strength: 16,
      dexterity: 10,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 6,
    },
    skills: { perception: 2 },
    senses: "Darkvision 60 ft.; passive Perception 12",
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 3 },
        description:
          "If the target is a Large or smaller creature and the elk moved 20+ feet straight toward it immediately before the hit, the target takes an extra 3 (1d6) Bludgeoning damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_frog",
    name: "Frog",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 1,
    speed: { walk: 20, swim: 20 },
    abilities: {
      strength: 1,
      dexterity: 13,
      constitution: 8,
      intelligence: 1,
      wisdom: 8,
      charisma: 3,
    },
    skills: { perception: 1, stealth: 3 },
    senses: "Darkvision 30 ft.; passive Perception 11",
    traits: [
      {
        name: "Amphibious",
        description: "The frog can breathe air and water.",
      },
      {
        name: "Standing Leap",
        description:
          "The frog's Long Jump is up to 10 feet and its High Jump is up to 5 feet with or without a running start.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_ape",
    name: "Giant Ape",
    size: "huge",
    cr: 7,
    xp: 2900,
    ac: 12,
    hitPoints: 168,
    speed: { walk: 40, climb: 40 },
    abilities: {
      strength: 23,
      dexterity: 14,
      constitution: 18,
      intelligence: 7,
      wisdom: 12,
      charisma: 7,
    },
    skills: { athletics: 9, perception: 4, survival: 4 },
    senses: "passive Perception 14",
    actions: [
      {
        name: "Fist",
        attackType: "melee",
        attackBonus: 9,
        reach: 10,
        damage: { type: "bludgeoning", dice: [10, 10, 10], flatBonus: 6 },
      },
      {
        name: "Boulder Toss",
        attackType: "ranged",
        attackBonus: 9,
        range: { normal: 90, long: 90 },
        damage: { type: "bludgeoning", dice: [6, 6, 6, 6, 6, 6, 6] },
        description:
          "Dexterity Saving Throw DC 17, each creature in a 5-foot-radius Sphere. If the target is a Large or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_badger",
    name: "Giant Badger",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 15,
    speed: { walk: 30, burrow: 10 },
    abilities: {
      strength: 13,
      dexterity: 10,
      constitution: 16,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4], flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_bat",
    name: "Giant Bat",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 22,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 14,
      dexterity: 16,
      constitution: 11,
      intelligence: 2,
      wisdom: 12,
      charisma: 6,
    },
    senses: "Blindsight 60 ft.; passive Perception 11",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_boar",
    name: "Giant Boar",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 13,
    hitPoints: 42,
    speed: { walk: 40 },
    abilities: {
      strength: 17,
      dexterity: 10,
      constitution: 16,
      intelligence: 3,
      wisdom: 11,
      charisma: 6,
    },
    senses: "passive Perception 8",
    traits: [
      {
        name: "Bloodied Fury",
        description: "The boar has Advantage on melee attack rolls while it is Bloodied.",
      },
    ],
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 3 },
        description:
          "If the target is a Large or smaller creature and the boar moved 20+ feet straight toward it immediately before the hit, the target takes an extra 7 (2d6) Piercing damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_centipede",
    name: "Giant Centipede",
    size: "small",
    cr: 0.25,
    xp: 50,
    ac: 14,
    hitPoints: 9,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 5,
      dexterity: 16,
      constitution: 11,
      intelligence: 1,
      wisdom: 12,
      charisma: 3,
    },
    senses: "Blindsight 30 ft.; passive Perception 8",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 1 },
        description:
          "The target has the Poisoned condition until the start of the centipede's next turn.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_constrictor_snake",
    name: "Giant Constrictor Snake",
    size: "huge",
    cr: 2,
    xp: 450,
    ac: 15,
    hitPoints: 60,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 19,
      dexterity: 10,
      constitution: 15,
      intelligence: 1,
      wisdom: 8,
      charisma: 3,
    },
    skills: { perception: 2 },
    senses: "Blindsight 10 ft.; passive Perception 12",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 4 },
      },
      {
        name: "Constrict",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "bludgeoning", dice: [8, 8], flatBonus: 4 },
        description:
          "Strength Saving Throw DC 14, one Large or smaller creature. The target has the Grappled condition (escape DC 14).",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_crab",
    name: "Giant Crab",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 18,
    hitPoints: 13,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 13,
      constitution: 13,
      intelligence: 1,
      wisdom: 9,
      charisma: 3,
    },
    skills: { stealth: 3 },
    senses: "Blindsight 30 ft.; passive Perception 9",
    traits: [
      {
        name: "Amphibious",
        description: "The crab can breathe air and water.",
      },
    ],
    actions: [
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 1 },
        description:
          "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 11) from one of two claws.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_crocodile",
    name: "Giant Crocodile",
    size: "huge",
    cr: 5,
    xp: 1800,
    ac: 14,
    hitPoints: 85,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 21,
      dexterity: 9,
      constitution: 17,
      intelligence: 2,
      wisdom: 12,
      charisma: 6,
    },
    skills: { stealth: 5 },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Hold Breath",
        description: "The crocodile can hold its breath for 1 hour.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 8,
        reach: 5,
        damage: { type: "piercing", dice: [10, 10, 10], flatBonus: 5 },
        description:
          "If the target is a Large or smaller creature, it has the Grappled condition (escape DC 15). While Grappled, the target has the Restrained condition and can't be targeted by the crocodile's Tail.",
      },
      {
        name: "Tail",
        attackType: "melee",
        attackBonus: 8,
        reach: 10,
        damage: { type: "bludgeoning", dice: [8, 8, 8], flatBonus: 5 },
        description: "If the target is a Large or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_fire_beetle",
    name: "Giant Fire Beetle",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 4,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 8,
      dexterity: 10,
      constitution: 12,
      intelligence: 1,
      wisdom: 7,
      charisma: 3,
    },
    senses: "Blindsight 30 ft.; passive Perception 8",
    traits: [
      {
        name: "Illumination",
        description:
          "The beetle sheds Bright Light in a 10-foot radius and Dim Light for an additional 10 feet.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 1,
        reach: 5,
        damage: { type: "fire", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_frog",
    name: "Giant Frog",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 11,
    hitPoints: 18,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 12,
      dexterity: 13,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    skills: { perception: 2, stealth: 4 },
    senses: "Darkvision 30 ft.; passive Perception 12",
    traits: [
      {
        name: "Amphibious",
        description: "The frog can breathe air and water.",
      },
      {
        name: "Standing Leap",
        description:
          "The frog's Long Jump is up to 20 feet and its High Jump is up to 10 feet with or without a running start.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
        description:
          "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 11).",
      },
      {
        name: "Swallow",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "acid", dice: [4, 4] },
        description:
          "The frog swallows a Small or smaller target it is grappling. While swallowed, the target has the Blinded and Restrained conditions.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_goat",
    name: "Giant Goat",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 11,
    hitPoints: 19,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 17,
      dexterity: 13,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 3 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 3 },
        description:
          "If the target is a Large or smaller creature and the goat moved 20+ feet straight toward it immediately before the hit, the target takes an extra 5 (2d4) Bludgeoning damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_hyena",
    name: "Giant Hyena",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 12,
    hitPoints: 45,
    speed: { walk: 50 },
    abilities: {
      strength: 16,
      dexterity: 14,
      constitution: 14,
      intelligence: 4,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 3 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_lizard",
    name: "Giant Lizard",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 15,
    hitPoints: 19,
    speed: { walk: 40, climb: 40 },
    abilities: {
      strength: 15,
      dexterity: 12,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    senses: "Darkvision 60 ft.; passive Perception 10",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The lizard can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_octopus",
    name: "Giant Octopus",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 11,
    hitPoints: 45,
    speed: { walk: 10, swim: 60 },
    abilities: {
      strength: 17,
      dexterity: 13,
      constitution: 13,
      intelligence: 5,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 4, stealth: 5 },
    senses: "Darkvision 60 ft.; passive Perception 14",
    traits: [
      {
        name: "Water Breathing",
        description:
          "The octopus can breathe only underwater. It can hold its breath for 1 hour outside water.",
      },
    ],
    actions: [
      {
        name: "Tentacles",
        attackType: "melee",
        attackBonus: 5,
        reach: 10,
        damage: { type: "bludgeoning", dice: [6, 6], flatBonus: 3 },
        description:
          "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 13) from all eight tentacles. While Grappled, the target has the Restrained condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_rat",
    name: "Giant Rat",
    size: "small",
    cr: 0.125,
    xp: 25,
    ac: 13,
    hitPoints: 7,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 7,
      dexterity: 16,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2 },
    senses: "Darkvision 60 ft.; passive Perception 12",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The rat has Advantage on an attack roll against a creature if at least one of the rat's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 3 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_scorpion",
    name: "Giant Scorpion",
    size: "large",
    cr: 3,
    xp: 700,
    ac: 15,
    hitPoints: 52,
    speed: { walk: 40 },
    abilities: {
      strength: 16,
      dexterity: 13,
      constitution: 15,
      intelligence: 1,
      wisdom: 9,
      charisma: 3,
    },
    senses: "Blindsight 60 ft.; passive Perception 9",
    actions: [
      {
        name: "Claw",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6], flatBonus: 3 },
        description:
          "If the target is a Large or smaller creature, it has the Grappled condition (escape DC 13) from one of two claws.",
      },
      {
        name: "Sting",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 3 },
        description: "Plus 11 (2d10) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_seahorse",
    name: "Giant Seahorse",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 14,
    hitPoints: 16,
    speed: { walk: 5, swim: 40 },
    abilities: {
      strength: 15,
      dexterity: 12,
      constitution: 11,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Water Breathing",
        description: "The seahorse can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [6, 6], flatBonus: 2 },
        description:
          "Deals 11 (2d8 + 2) Bludgeoning damage if the seahorse moved 20+ feet straight toward the target immediately before the hit.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_shark",
    name: "Giant Shark",
    size: "huge",
    cr: 5,
    xp: 1800,
    ac: 13,
    hitPoints: 92,
    speed: { walk: 5, swim: 60 },
    abilities: {
      strength: 23,
      dexterity: 11,
      constitution: 21,
      intelligence: 1,
      wisdom: 10,
      charisma: 5,
    },
    skills: { perception: 3 },
    senses: "Blindsight 60 ft.; passive Perception 13",
    traits: [
      {
        name: "Water Breathing",
        description: "The shark can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 9,
        reach: 5,
        damage: { type: "piercing", dice: [10, 10, 10], flatBonus: 6 },
        description:
          "The shark has Advantage on the attack roll if the target doesn't have all its Hit Points.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_spider",
    name: "Giant Spider",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 14,
    hitPoints: 26,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 14,
      dexterity: 16,
      constitution: 12,
      intelligence: 2,
      wisdom: 11,
      charisma: 4,
    },
    skills: { perception: 4, stealth: 7 },
    senses: "Darkvision 60 ft.; passive Perception 14",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The spider can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
      {
        name: "Web Walker",
        description:
          "The spider ignores movement restrictions caused by webs, and it knows the location of any other creature in contact with the same web.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 3 },
        description: "Plus 7 (2d6) Poison damage.",
      },
      {
        name: "Web",
        attackType: "ranged",
        attackBonus: 5,
        range: { normal: 60, long: 60 },
        damage: { type: "bludgeoning" },
        description:
          "Dexterity Saving Throw DC 13, one creature. The target has the Restrained condition until the web is destroyed (AC 10; HP 5; Vulnerability to Fire damage).",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_toad",
    name: "Giant Toad",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 11,
    hitPoints: 39,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 15,
      dexterity: 13,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    senses: "Darkvision 60 ft.; passive Perception 10",
    traits: [
      {
        name: "Amphibious",
        description: "The toad can breathe air and water.",
      },
      {
        name: "Standing Leap",
        description:
          "The toad's Long Jump is up to 20 feet and its High Jump is up to 10 feet with or without a running start.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
        description:
          "Plus 5 (2d4) Poison damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12).",
      },
      {
        name: "Swallow",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "acid", dice: [6, 6, 6] },
        description:
          "The toad swallows a Medium or smaller target it is grappling. While swallowed, the target has the Blinded and Restrained conditions.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_venomous_snake",
    name: "Giant Venomous Snake",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 14,
    hitPoints: 11,
    speed: { walk: 40, swim: 40 },
    abilities: {
      strength: 10,
      dexterity: 18,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    skills: { perception: 2 },
    senses: "Blindsight 10 ft.; passive Perception 12",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "piercing", dice: [4], flatBonus: 4 },
        description: "Plus 4 (1d8) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_wasp",
    name: "Giant Wasp",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 13,
    hitPoints: 22,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 10,
      dexterity: 14,
      constitution: 10,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Flyby",
        description:
          "The wasp doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
      },
    ],
    actions: [
      {
        name: "Sting",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
        description: "Plus 5 (2d4) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_weasel",
    name: "Giant Weasel",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 13,
    hitPoints: 9,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 11,
      dexterity: 17,
      constitution: 10,
      intelligence: 4,
      wisdom: 12,
      charisma: 5,
    },
    skills: { acrobatics: 5, perception: 3, stealth: 5 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 3 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_giant_wolf_spider",
    name: "Giant Wolf Spider",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 11,
    speed: { walk: 40, climb: 40 },
    abilities: {
      strength: 12,
      dexterity: 16,
      constitution: 13,
      intelligence: 3,
      wisdom: 12,
      charisma: 4,
    },
    skills: { perception: 3, stealth: 7 },
    senses: "Blindsight 10 ft., Darkvision 60 ft.; passive Perception 13",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The spider can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 3 },
        description: "Plus 5 (2d4) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_goat",
    name: "Goat",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 4,
    speed: { walk: 40, climb: 30 },
    abilities: {
      strength: 11,
      dexterity: 10,
      constitution: 11,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    skills: { perception: 2 },
    senses: "Darkvision 60 ft.; passive Perception 12",
    actions: [
      {
        name: "Ram",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "bludgeoning", flatBonus: 1 },
        description:
          "Deals 2 (1d4) Bludgeoning damage if the goat moved 20+ feet straight toward the target immediately before the hit.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_hawk",
    name: "Hawk",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 1,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 5,
      dexterity: 16,
      constitution: 8,
      intelligence: 2,
      wisdom: 14,
      charisma: 6,
    },
    skills: { perception: 6 },
    senses: "passive Perception 16",
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_hippopotamus",
    name: "Hippopotamus",
    size: "large",
    cr: 4,
    xp: 1100,
    ac: 14,
    hitPoints: 82,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 21,
      dexterity: 7,
      constitution: 15,
      intelligence: 2,
      wisdom: 12,
      charisma: 4,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Hold Breath",
        description: "The hippopotamus can hold its breath for 10 minutes.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 7,
        reach: 5,
        damage: { type: "piercing", dice: [10, 10], flatBonus: 5 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_hunter_shark",
    name: "Hunter Shark",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 12,
    hitPoints: 45,
    speed: { walk: 5, swim: 40 },
    abilities: {
      strength: 18,
      dexterity: 14,
      constitution: 15,
      intelligence: 1,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2 },
    senses: "Blindsight 60 ft.; passive Perception 12",
    traits: [
      {
        name: "Water Breathing",
        description: "The shark can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6, 6], flatBonus: 4 },
        description:
          "The shark has Advantage on the attack roll if the target doesn't have all its Hit Points.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_hyena",
    name: "Hyena",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 5,
    speed: { walk: 50 },
    abilities: {
      strength: 11,
      dexterity: 13,
      constitution: 12,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The hyena has Advantage on an attack roll against a creature if at least one of the hyena's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [6] },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_jackal",
    name: "Jackal",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 40 },
    abilities: {
      strength: 8,
      dexterity: 15,
      constitution: 11,
      intelligence: 3,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 5, stealth: 4 },
    senses: "Darkvision 90 ft.; passive Perception 15",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 1,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: -1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_killer_whale",
    name: "Killer Whale",
    size: "huge",
    cr: 3,
    xp: 700,
    ac: 12,
    hitPoints: 90,
    speed: { walk: 5, swim: 60 },
    abilities: {
      strength: 19,
      dexterity: 14,
      constitution: 13,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "Blindsight 120 ft.; passive Perception 13",
    traits: [
      {
        name: "Hold Breath",
        description: "The whale can hold its breath for 30 minutes.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [6, 6, 6, 6, 6], flatBonus: 4 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_lion",
    name: "Lion",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 12,
    hitPoints: 22,
    speed: { walk: 50 },
    abilities: {
      strength: 17,
      dexterity: 15,
      constitution: 11,
      intelligence: 3,
      wisdom: 12,
      charisma: 8,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The lion has Advantage on an attack roll against a creature if at least one of the lion's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
      {
        name: "Running Leap",
        description: "With a 10-foot running start, the lion can Long Jump up to 25 feet.",
      },
    ],
    actions: [
      {
        name: "Rend",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [8], flatBonus: 3 },
      },
      {
        name: "Roar",
        attackType: "melee",
        attackBonus: 5,
        reach: 15,
        damage: { type: "psychic" },
        description:
          "Wisdom Saving Throw DC 11, one creature within 15 feet. The target has the Frightened condition until the start of the lion's next turn.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_lizard",
    name: "Lizard",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 2,
    speed: { walk: 20, climb: 20 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 10,
      intelligence: 1,
      wisdom: 8,
      charisma: 3,
    },
    senses: "Darkvision 30 ft.; passive Perception 9",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The lizard can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_mammoth",
    name: "Mammoth",
    size: "huge",
    cr: 6,
    xp: 2300,
    ac: 13,
    hitPoints: 126,
    speed: { walk: 50 },
    abilities: {
      strength: 24,
      dexterity: 9,
      constitution: 21,
      intelligence: 3,
      wisdom: 11,
      charisma: 6,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 10,
        reach: 10,
        damage: { type: "piercing", dice: [10, 10], flatBonus: 7 },
        description:
          "If the target is a Huge or smaller creature and the mammoth moved 20+ feet straight toward it immediately before the hit, the target has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_mastiff",
    name: "Mastiff",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 12,
    hitPoints: 5,
    speed: { walk: 40 },
    abilities: {
      strength: 13,
      dexterity: 14,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 5 },
    senses: "Darkvision 60 ft.; passive Perception 15",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 1 },
        description: "If the target is a Medium or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_mule",
    name: "Mule",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 10,
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 14,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 10,
      charisma: 5,
    },
    senses: "passive Perception 10",
    traits: [
      {
        name: "Beast of Burden",
        description:
          "The mule counts as one size larger for the purpose of determining its carrying capacity.",
      },
    ],
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_octopus",
    name: "Octopus",
    size: "small",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 3,
    speed: { walk: 5, swim: 30 },
    abilities: {
      strength: 4,
      dexterity: 15,
      constitution: 11,
      intelligence: 3,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2, stealth: 6 },
    senses: "Darkvision 30 ft.; passive Perception 12",
    traits: [
      {
        name: "Compression",
        description:
          "The octopus can move through a space as narrow as 1 inch without expending extra movement to do so.",
      },
      {
        name: "Water Breathing",
        description: "The octopus can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Tentacles",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_owl",
    name: "Owl",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 1,
    speed: { walk: 5, fly: 60 },
    abilities: {
      strength: 3,
      dexterity: 13,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    skills: { perception: 5, stealth: 5 },
    senses: "Darkvision 120 ft.; passive Perception 15",
    traits: [
      {
        name: "Flyby",
        description:
          "The owl doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
      },
    ],
    actions: [
      {
        name: "Talons",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "slashing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_panther",
    name: "Panther",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 13,
    speed: { walk: 50, climb: 40 },
    abilities: {
      strength: 14,
      dexterity: 16,
      constitution: 10,
      intelligence: 3,
      wisdom: 14,
      charisma: 7,
    },
    skills: { perception: 4, stealth: 7 },
    senses: "Darkvision 60 ft.; passive Perception 14",
    actions: [
      {
        name: "Rend",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [6], flatBonus: 3 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_piranha",
    name: "Piranha",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 1,
    speed: { walk: 5, swim: 40 },
    abilities: {
      strength: 2,
      dexterity: 16,
      constitution: 9,
      intelligence: 1,
      wisdom: 7,
      charisma: 2,
    },
    senses: "Darkvision 60 ft.; passive Perception 8",
    traits: [
      {
        name: "Water Breathing",
        description: "The piranha can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description:
          "The piranha has Advantage on the attack roll if the target doesn't have all its Hit Points.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_plesiosaurus",
    name: "Plesiosaurus",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 13,
    hitPoints: 68,
    speed: { walk: 20, swim: 40 },
    abilities: {
      strength: 18,
      dexterity: 15,
      constitution: 16,
      intelligence: 2,
      wisdom: 12,
      charisma: 5,
    },
    skills: { perception: 3, stealth: 4 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Hold Breath",
        description: "The plesiosaurus can hold its breath for 1 hour.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 6,
        reach: 10,
        damage: { type: "piercing", dice: [6, 6], flatBonus: 4 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_polar_bear",
    name: "Polar Bear",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 12,
    hitPoints: 42,
    speed: { walk: 40, swim: 40 },
    abilities: {
      strength: 20,
      dexterity: 14,
      constitution: 16,
      intelligence: 2,
      wisdom: 13,
      charisma: 7,
    },
    skills: { perception: 5, stealth: 4 },
    senses: "Darkvision 60 ft.; passive Perception 15",
    actions: [
      {
        name: "Rend",
        attackType: "melee",
        attackBonus: 7,
        reach: 5,
        damage: { type: "slashing", dice: [8], flatBonus: 5 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_pony",
    name: "Pony",
    size: "medium",
    cr: 0.125,
    xp: 25,
    ac: 10,
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 15,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 11,
      charisma: 7,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_pteranodon",
    name: "Pteranodon",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 13,
    hitPoints: 13,
    speed: { walk: 10, fly: 60 },
    abilities: {
      strength: 12,
      dexterity: 15,
      constitution: 10,
      intelligence: 2,
      wisdom: 9,
      charisma: 5,
    },
    skills: { perception: 1 },
    senses: "passive Perception 11",
    traits: [
      {
        name: "Flyby",
        description:
          "The pteranodon doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_rat",
    name: "Rat",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 1,
    speed: { walk: 20, climb: 20 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 9,
      intelligence: 2,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2 },
    senses: "Darkvision 30 ft.; passive Perception 12",
    traits: [
      {
        name: "Agile",
        description:
          "The rat doesn't provoke an Opportunity Attack when it moves out of an enemy's reach.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_raven",
    name: "Raven",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 2,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 2,
      dexterity: 14,
      constitution: 10,
      intelligence: 5,
      wisdom: 13,
      charisma: 6,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Mimicry",
        description:
          "The raven can mimic simple sounds it has heard, such as a whisper or chitter. A hearer can discern the sounds are imitations with a successful DC 10 Wisdom (Insight) check.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_reef_shark",
    name: "Reef Shark",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 12,
    hitPoints: 22,
    speed: { walk: 5, swim: 30 },
    abilities: {
      strength: 14,
      dexterity: 15,
      constitution: 13,
      intelligence: 1,
      wisdom: 10,
      charisma: 4,
    },
    skills: { perception: 2 },
    senses: "Blindsight 30 ft.; passive Perception 12",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The shark has Advantage on an attack roll against a creature if at least one of the shark's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
      {
        name: "Water Breathing",
        description: "The shark can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4], flatBonus: 2 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_rhinoceros",
    name: "Rhinoceros",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 13,
    hitPoints: 45,
    speed: { walk: 40 },
    abilities: {
      strength: 21,
      dexterity: 8,
      constitution: 15,
      intelligence: 2,
      wisdom: 12,
      charisma: 6,
    },
    senses: "passive Perception 11",
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 7,
        reach: 5,
        damage: { type: "piercing", dice: [8, 8], flatBonus: 5 },
        description:
          "If target is a Large or smaller creature and the rhinoceros moved 20+ feet straight toward it immediately before the hit, the target takes an extra 9 (2d8) Piercing damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_riding_horse",
    name: "Riding Horse",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 11,
    hitPoints: 13,
    speed: { walk: 60 },
    abilities: {
      strength: 16,
      dexterity: 13,
      constitution: 12,
      intelligence: 2,
      wisdom: 11,
      charisma: 7,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "bludgeoning", dice: [8], flatBonus: 3 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_saber_toothed_tiger",
    name: "Saber-Toothed Tiger",
    size: "large",
    cr: 2,
    xp: 450,
    ac: 13,
    hitPoints: 52,
    speed: { walk: 40 },
    abilities: {
      strength: 18,
      dexterity: 17,
      constitution: 15,
      intelligence: 3,
      wisdom: 12,
      charisma: 8,
    },
    skills: { perception: 5, stealth: 7 },
    senses: "Darkvision 60 ft.; passive Perception 15",
    traits: [
      {
        name: "Running Leap",
        description: "With a 10-foot running start, the tiger can Long Jump up to 25 feet.",
      },
    ],
    actions: [
      {
        name: "Rend",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 4 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_scorpion",
    name: "Scorpion",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 11,
    hitPoints: 1,
    speed: { walk: 10 },
    abilities: {
      strength: 2,
      dexterity: 11,
      constitution: 8,
      intelligence: 1,
      wisdom: 8,
      charisma: 2,
    },
    senses: "Blindsight 10 ft.; passive Perception 9",
    actions: [
      {
        name: "Sting",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description: "Plus 3 (1d6) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_seahorse",
    name: "Seahorse",
    size: "tiny",
    cr: 0,
    xp: 0,
    ac: 12,
    hitPoints: 1,
    speed: { walk: 5, swim: 20 },
    abilities: {
      strength: 1,
      dexterity: 12,
      constitution: 8,
      intelligence: 1,
      wisdom: 10,
      charisma: 2,
    },
    skills: { perception: 2, stealth: 5 },
    senses: "passive Perception 12",
    traits: [
      {
        name: "Water Breathing",
        description: "The seahorse can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bubble Dash",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "bludgeoning" },
        description:
          "While underwater, the seahorse moves up to its Swim Speed without provoking Opportunity Attacks.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_spider",
    name: "Spider",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 12,
    hitPoints: 1,
    speed: { walk: 20, climb: 20 },
    abilities: {
      strength: 2,
      dexterity: 14,
      constitution: 8,
      intelligence: 1,
      wisdom: 10,
      charisma: 2,
    },
    skills: { stealth: 4 },
    senses: "Darkvision 30 ft.; passive Perception 10",
    traits: [
      {
        name: "Spider Climb",
        description:
          "The spider can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
      {
        name: "Web Walker",
        description:
          "The spider ignores movement restrictions caused by webs, and the spider knows the location of any other creature in contact with the same web.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
        description: "Plus 2 (1d4) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_swarm_of_bats",
    name: "Swarm of Bats",
    size: "large",
    cr: 0.25,
    xp: 50,
    ac: 12,
    hitPoints: 11,
    speed: { walk: 5, fly: 30 },
    abilities: {
      strength: 5,
      dexterity: 15,
      constitution: 10,
      intelligence: 2,
      wisdom: 12,
      charisma: 4,
    },
    senses: "Blindsight 60 ft.; passive Perception 11",
    traits: [
      {
        name: "Swarm",
        description:
          "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny bat. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
    ],
    actions: [
      {
        name: "Bites",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4] },
        description: "Deals 2 (1d4) Piercing damage if the swarm is Bloodied.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_swarm_of_insects",
    name: "Swarm of Insects",
    size: "medium",
    cr: 0.5,
    xp: 100,
    ac: 11,
    hitPoints: 19,
    speed: { walk: 20, climb: 20, fly: 20 },
    abilities: {
      strength: 3,
      dexterity: 13,
      constitution: 14,
      intelligence: 1,
      wisdom: 7,
      charisma: 1,
    },
    senses: "Blindsight 30 ft.; passive Perception 8",
    traits: [
      {
        name: "Spider Climb",
        description:
          "If the swarm has a Climb Speed, the swarm can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
      },
      {
        name: "Swarm",
        description:
          "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny insect. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
    ],
    actions: [
      {
        name: "Bites",
        attackType: "melee",
        attackBonus: 3,
        reach: 5,
        damage: { type: "poison", dice: [4, 4], flatBonus: 1 },
        description: "Deals 3 (1d4 + 1) Poison damage if the swarm is Bloodied.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_swarm_of_piranhas",
    name: "Swarm of Piranhas",
    size: "medium",
    cr: 1,
    xp: 200,
    ac: 13,
    hitPoints: 28,
    speed: { walk: 5, swim: 40 },
    abilities: {
      strength: 13,
      dexterity: 16,
      constitution: 9,
      intelligence: 1,
      wisdom: 7,
      charisma: 2,
    },
    senses: "Darkvision 60 ft.; passive Perception 8",
    traits: [
      {
        name: "Swarm",
        description:
          "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny piranha. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
      {
        name: "Water Breathing",
        description: "The swarm can breathe only underwater.",
      },
    ],
    actions: [
      {
        name: "Bites",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4], flatBonus: 3 },
        description:
          "The swarm has Advantage on the attack roll if the target doesn't have all its Hit Points. Deals 5 (1d4 + 3) Piercing damage if the swarm is Bloodied.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_swarm_of_rats",
    name: "Swarm of Rats",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 10,
    hitPoints: 14,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 9,
      dexterity: 11,
      constitution: 9,
      intelligence: 2,
      wisdom: 10,
      charisma: 3,
    },
    senses: "Darkvision 30 ft.; passive Perception 10",
    traits: [
      {
        name: "Swarm",
        description:
          "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny rat. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
    ],
    actions: [
      {
        name: "Bites",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [4, 4] },
        description: "Deals 2 (1d4) Piercing damage if the swarm is Bloodied.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_swarm_of_ravens",
    name: "Swarm of Ravens",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 12,
    hitPoints: 11,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 6,
      dexterity: 14,
      constitution: 12,
      intelligence: 5,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 5 },
    senses: "passive Perception 15",
    traits: [
      {
        name: "Swarm",
        description:
          "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny raven. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
    ],
    actions: [
      {
        name: "Beaks",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
        description: "Deals 2 (1d4) Piercing damage if the swarm is Bloodied.",
      },
      {
        name: "Cacophony",
        attackType: "melee",
        attackBonus: 0,
        reach: 5,
        damage: { type: "psychic" },
        description:
          "Recharge 6. Wisdom Saving Throw DC 10, one creature in the swarm's space. The target has the Deafened condition until the start of the swarm's next turn. While Deafened, the target also has Disadvantage on ability checks and attack rolls.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_swarm_of_venomous_snakes",
    name: "Swarm of Venomous Snakes",
    size: "medium",
    cr: 2,
    xp: 450,
    ac: 14,
    hitPoints: 36,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 8,
      dexterity: 18,
      constitution: 11,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    senses: "Blindsight 10 ft.; passive Perception 10",
    traits: [
      {
        name: "Swarm",
        description:
          "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny snake. The swarm can't regain Hit Points or gain Temporary Hit Points.",
      },
    ],
    actions: [
      {
        name: "Bites",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "piercing", dice: [8], flatBonus: 4 },
        description:
          "Plus 10 (3d6) Poison damage. Deals 6 (1d4 + 4) Piercing damage if the swarm is Bloodied.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_tiger",
    name: "Tiger",
    size: "large",
    cr: 1,
    xp: 200,
    ac: 13,
    hitPoints: 30,
    speed: { walk: 40 },
    abilities: {
      strength: 17,
      dexterity: 16,
      constitution: 14,
      intelligence: 3,
      wisdom: 12,
      charisma: 8,
    },
    skills: { perception: 3, stealth: 7 },
    senses: "Darkvision 60 ft.; passive Perception 13",
    actions: [
      {
        name: "Rend",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "slashing", dice: [6, 6], flatBonus: 3 },
        description: "If the target is a Large or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_triceratops",
    name: "Triceratops",
    size: "huge",
    cr: 5,
    xp: 1800,
    ac: 14,
    hitPoints: 114,
    speed: { walk: 50 },
    abilities: {
      strength: 22,
      dexterity: 9,
      constitution: 17,
      intelligence: 2,
      wisdom: 11,
      charisma: 5,
    },
    senses: "passive Perception 10",
    actions: [
      {
        name: "Gore",
        attackType: "melee",
        attackBonus: 9,
        reach: 5,
        damage: { type: "piercing", dice: [12, 12], flatBonus: 6 },
        description:
          "If the target is Huge or smaller and the triceratops moved 20+ feet straight toward it immediately before the hit, the target takes an extra 9 (2d8) Piercing damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_tyrannosaurus_rex",
    name: "Tyrannosaurus Rex",
    size: "huge",
    cr: 8,
    xp: 3900,
    ac: 13,
    hitPoints: 136,
    speed: { walk: 50 },
    abilities: {
      strength: 25,
      dexterity: 10,
      constitution: 19,
      intelligence: 2,
      wisdom: 12,
      charisma: 9,
    },
    skills: { perception: 4 },
    senses: "passive Perception 14",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 10,
        reach: 10,
        damage: { type: "piercing", dice: [12, 12, 12, 12], flatBonus: 7 },
        description:
          "If the target is a Large or smaller creature, it has the Grappled condition (escape DC 17). While Grappled, the target has the Restrained condition and can't be targeted by the tyrannosaurus's Tail.",
      },
      {
        name: "Tail",
        attackType: "melee",
        attackBonus: 10,
        reach: 15,
        damage: { type: "bludgeoning", dice: [8, 8, 8, 8], flatBonus: 7 },
        description: "If the target is a Huge or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_venomous_snake",
    name: "Venomous Snake",
    size: "tiny",
    cr: 0.125,
    xp: 25,
    ac: 12,
    hitPoints: 5,
    speed: { walk: 30, swim: 30 },
    abilities: {
      strength: 2,
      dexterity: 15,
      constitution: 11,
      intelligence: 1,
      wisdom: 10,
      charisma: 3,
    },
    senses: "Blindsight 10 ft.; passive Perception 10",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [4], flatBonus: 2 },
        description: "Plus 3 (1d6) Poison damage.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_vulture",
    name: "Vulture",
    size: "medium",
    cr: 0,
    xp: 10,
    ac: 10,
    hitPoints: 5,
    speed: { walk: 10, fly: 50 },
    abilities: {
      strength: 7,
      dexterity: 10,
      constitution: 13,
      intelligence: 2,
      wisdom: 12,
      charisma: 4,
    },
    skills: { perception: 3 },
    senses: "passive Perception 13",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The vulture has Advantage on an attack roll against a creature if at least one of the vulture's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Beak",
        attackType: "melee",
        attackBonus: 2,
        reach: 5,
        damage: { type: "piercing", dice: [4] },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_warhorse",
    name: "Warhorse",
    size: "large",
    cr: 0.5,
    xp: 100,
    ac: 11,
    hitPoints: 19,
    speed: { walk: 60 },
    abilities: {
      strength: 18,
      dexterity: 12,
      constitution: 13,
      intelligence: 2,
      wisdom: 12,
      charisma: 7,
    },
    senses: "passive Perception 11",
    actions: [
      {
        name: "Hooves",
        attackType: "melee",
        attackBonus: 6,
        reach: 5,
        damage: { type: "bludgeoning", dice: [4, 4], flatBonus: 4 },
        description:
          "If the target is a Large or smaller creature and the horse moved 20+ feet straight toward it immediately before the hit, the target takes an extra 5 (2d4) Bludgeoning damage and has the Prone condition.",
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_weasel",
    name: "Weasel",
    size: "tiny",
    cr: 0,
    xp: 10,
    ac: 13,
    hitPoints: 1,
    speed: { walk: 30, climb: 30 },
    abilities: {
      strength: 3,
      dexterity: 16,
      constitution: 8,
      intelligence: 2,
      wisdom: 12,
      charisma: 3,
    },
    skills: { acrobatics: 5, perception: 3, stealth: 5 },
    senses: "Darkvision 60 ft., passive Perception 13",
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 5,
        reach: 5,
        damage: { type: "piercing", flatBonus: 1 },
      },
    ],
    source: "srd52",
  },
  {
    id: "srd52_wolf",
    name: "Wolf",
    size: "medium",
    cr: 0.25,
    xp: 50,
    ac: 12,
    hitPoints: 11,
    speed: { walk: 40 },
    abilities: {
      strength: 14,
      dexterity: 15,
      constitution: 12,
      intelligence: 3,
      wisdom: 12,
      charisma: 6,
    },
    skills: { perception: 5, stealth: 4 },
    senses: "Darkvision 60 ft., passive Perception 15",
    traits: [
      {
        name: "Pack Tactics",
        description:
          "The wolf has Advantage on attack rolls against a creature if at least one of the wolf's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition.",
      },
    ],
    actions: [
      {
        name: "Bite",
        attackType: "melee",
        attackBonus: 4,
        reach: 5,
        damage: { type: "piercing", dice: [6], flatBonus: 2 },
        description: "If the target is a Medium or smaller creature, it has the Prone condition.",
      },
    ],
    source: "srd52",
  },
]
