import type { TemplateItem } from "@src/lib/dnd"

/**
 * Weapon templates from D&D 5.2.1 SRD
 * Source: SRD_CC_v5.2.1-extracted.md lines 8909-8955
 */
export const srd52Weapons: TemplateItem[] = [
  // Simple Melee Weapons
  {
    name: "Club",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "bludgeoning" }],
    mastery: "slow",
    martial: false,
    light: true,
  },
  {
    name: "Dagger",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "piercing" }],
    finesse: true,
    normal_range: 20,
    long_range: 60,
    mastery: "nick",
    martial: false,
    light: true,
  },
  {
    name: "Greatclub",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "bludgeoning" }],
    mastery: "push",
    martial: false,
    two_handed: true,
  },
  {
    name: "Handaxe",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 6, type: "slashing" }],
    normal_range: 20,
    long_range: 60,
    mastery: "vex",
    martial: false,
    light: true,
  },
  {
    name: "Javelin",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    normal_range: 30,
    long_range: 120,
    mastery: "slow",
    martial: false,
  },
  {
    name: "Light Hammer",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 4, type: "bludgeoning" }],
    normal_range: 20,
    long_range: 60,
    mastery: "nick",
    martial: false,
    light: true,
  },
  {
    name: "Mace",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "bludgeoning" }],
    mastery: "sap",
    martial: false,
  },
  {
    name: "Quarterstaff",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "bludgeoning" }],
    mastery: "topple",
    martial: false,
    versatile: "1d8",
  },
  {
    name: "Sickle",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "slashing" }],
    mastery: "nick",
    martial: false,
    light: true,
  },
  {
    name: "Spear",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    normal_range: 20,
    long_range: 60,
    mastery: "sap",
    martial: false,
    versatile: "1d8",
  },

  // Simple Ranged Weapons
  {
    name: "Dart",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 4, type: "piercing" }],
    finesse: true,
    normal_range: 20,
    long_range: 60,
    mastery: "vex",
    martial: false,
  },
  {
    name: "Light Crossbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    normal_range: 80,
    long_range: 320,
    starting_ammo: 20,
    mastery: "slow",
    martial: false,
    ammunition: true,
    loading: true,
    two_handed: true,
  },
  {
    name: "Shortbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    normal_range: 80,
    long_range: 320,
    starting_ammo: 20,
    mastery: "vex",
    martial: false,
    ammunition: true,
    two_handed: true,
  },
  {
    name: "Sling",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 4, type: "bludgeoning" }],
    normal_range: 30,
    long_range: 120,
    starting_ammo: 20,
    mastery: "slow",
    martial: false,
    ammunition: true,
  },

  // Martial Melee Weapons
  {
    name: "Battleaxe",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "slashing" }],
    mastery: "topple",
    martial: true,
    versatile: "1d10",
  },
  {
    name: "Flail",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "bludgeoning" }],
    mastery: "sap",
    martial: true,
  },
  {
    name: "Glaive",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "slashing" }],
    mastery: "graze",
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Greataxe",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 12, type: "slashing" }],
    mastery: "cleave",
    martial: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Greatsword",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 2, die_value: 6, type: "slashing" }],
    mastery: "graze",
    martial: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Halberd",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "slashing" }],
    mastery: "cleave",
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Lance",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "piercing" }],
    mastery: "topple",
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Longsword",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "slashing" }],
    mastery: "sap",
    martial: true,
    versatile: "1d10",
  },
  {
    name: "Maul",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 2, die_value: 6, type: "bludgeoning" }],
    mastery: "topple",
    martial: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Morningstar",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    mastery: "sap",
    martial: true,
  },
  {
    name: "Pike",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "piercing" }],
    mastery: "push",
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Rapier",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    finesse: true,
    mastery: "vex",
    martial: true,
  },
  {
    name: "Scimitar",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "slashing" }],
    finesse: true,
    mastery: "nick",
    martial: true,
    light: true,
  },
  {
    name: "Shortsword",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    finesse: true,
    mastery: "vex",
    martial: true,
    light: true,
  },
  {
    name: "Trident",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    normal_range: 20,
    long_range: 60,
    mastery: "topple",
    martial: true,
    versatile: "1d10",
  },
  {
    name: "Warhammer",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "bludgeoning" }],
    mastery: "push",
    martial: true,
    versatile: "1d10",
  },
  {
    name: "War Pick",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    mastery: "sap",
    martial: true,
    versatile: "1d10",
  },
  {
    name: "Whip",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "slashing" }],
    finesse: true,
    mastery: "slow",
    martial: true,
    reach: true,
  },

  // Martial Ranged Weapons
  {
    name: "Blowgun",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 1, type: "piercing" }],
    normal_range: 25,
    long_range: 100,
    starting_ammo: 50,
    mastery: "vex",
    martial: true,
    ammunition: true,
    loading: true,
  },
  {
    name: "Hand Crossbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    normal_range: 30,
    long_range: 120,
    starting_ammo: 20,
    mastery: "vex",
    martial: true,
    ammunition: true,
    light: true,
    loading: true,
  },
  {
    name: "Heavy Crossbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 10, type: "piercing" }],
    normal_range: 100,
    long_range: 400,
    starting_ammo: 20,
    mastery: "push",
    martial: true,
    ammunition: true,
    heavy: true,
    loading: true,
    two_handed: true,
  },
  {
    name: "Longbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    normal_range: 150,
    long_range: 600,
    starting_ammo: 20,
    mastery: "slow",
    martial: true,
    ammunition: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Musket",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 12, type: "piercing" }],
    normal_range: 40,
    long_range: 120,
    starting_ammo: 10,
    mastery: "slow",
    martial: true,
    ammunition: true,
    loading: true,
    two_handed: true,
  },
  {
    name: "Pistol",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 10, type: "piercing" }],
    normal_range: 30,
    long_range: 90,
    starting_ammo: 10,
    mastery: "vex",
    martial: true,
    ammunition: true,
    loading: true,
  },
]
