import type { TemplateItem } from "@src/lib/dnd"

/**
 * Weapon templates from D&D 5.1 SRD
 * Source: SRD_CC_v5.1-extracted.md lines 4656-4703
 * Note: v5.1 does not have mastery properties
 */
export const srd51Weapons: TemplateItem[] = [
  // Simple Melee Weapons
  {
    name: "Club",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "bludgeoning" }],
    martial: false,
    light: true,
  },
  {
    name: "Dagger",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 4, type: "piercing" }],
    finesse: true,
    light: true,
    normal_range: 20,
    long_range: 60,
    martial: false,
  },
  {
    name: "Greatclub",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "bludgeoning" }],
    martial: false,
    two_handed: true,
  },
  {
    name: "Handaxe",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 6, type: "slashing" }],
    light: true,
    normal_range: 20,
    long_range: 60,
    martial: false,
  },
  {
    name: "Javelin",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    normal_range: 30,
    long_range: 120,
    martial: false,
  },
  {
    name: "Light hammer",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 4, type: "bludgeoning" }],
    light: true,
    normal_range: 20,
    long_range: 60,
    martial: false,
  },
  {
    name: "Mace",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "bludgeoning" }],
    martial: false,
  },
  {
    name: "Quarterstaff",
    category: "weapon",
    weapon_type: "melee",
    damage: [
      { num_dice: 1, die_value: 6, type: "bludgeoning" },
      { num_dice: 1, die_value: 8, type: "bludgeoning", versatile: true },
    ],
    martial: false,
  },
  {
    name: "Sickle",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "slashing" }],
    martial: false,
    light: true,
  },
  {
    name: "Spear",
    category: "weapon",
    weapon_type: "thrown",
    damage: [
      { num_dice: 1, die_value: 6, type: "piercing" },
      { num_dice: 1, die_value: 8, type: "piercing", versatile: true },
    ],
    normal_range: 20,
    long_range: 60,
    martial: false,
  },

  // Simple Ranged Weapons
  {
    name: "Crossbow, light",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    starting_ammo: 20,
    martial: false,
    ammunition: true,
    loading: true,
    two_handed: true,
    normal_range: 80,
    long_range: 320,
  },
  {
    name: "Dart",
    category: "weapon",
    weapon_type: "thrown",
    damage: [{ num_dice: 1, die_value: 4, type: "piercing" }],
    finesse: true,
    normal_range: 20,
    long_range: 60,
    martial: false,
  },
  {
    name: "Shortbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    starting_ammo: 20,
    martial: false,
    ammunition: true,
    two_handed: true,
    normal_range: 80,
    long_range: 320,
  },
  {
    name: "Sling",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 4, type: "bludgeoning" }],
    starting_ammo: 20,
    martial: false,
    ammunition: true,
    normal_range: 30,
    long_range: 120,
  },

  // Martial Melee Weapons
  {
    name: "Battleaxe",
    category: "weapon",
    weapon_type: "melee",
    damage: [
      { num_dice: 1, die_value: 8, type: "slashing" },
      { num_dice: 1, die_value: 10, type: "slashing", versatile: true },
    ],
    martial: true,
  },
  {
    name: "Flail",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "bludgeoning" }],
    martial: true,
  },
  {
    name: "Glaive",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "slashing" }],
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Greataxe",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 12, type: "slashing" }],
    martial: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Greatsword",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 2, die_value: 6, type: "slashing" }],
    martial: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Halberd",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "slashing" }],
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Lance",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 12, type: "piercing" }],
    martial: true,
    reach: true,
  },
  {
    name: "Longsword",
    category: "weapon",
    weapon_type: "melee",
    damage: [
      { num_dice: 1, die_value: 8, type: "slashing" },
      { num_dice: 1, die_value: 10, type: "slashing", versatile: true },
    ],
    martial: true,
  },
  {
    name: "Maul",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 2, die_value: 6, type: "bludgeoning" }],
    martial: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Morningstar",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    martial: true,
  },
  {
    name: "Pike",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 10, type: "piercing" }],
    martial: true,
    heavy: true,
    reach: true,
    two_handed: true,
  },
  {
    name: "Rapier",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    finesse: true,
    martial: true,
  },
  {
    name: "Scimitar",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "slashing" }],
    finesse: true,
    light: true,
    martial: true,
  },
  {
    name: "Shortsword",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    finesse: true,
    light: true,
    martial: true,
  },
  {
    name: "Trident",
    category: "weapon",
    weapon_type: "thrown",
    damage: [
      { num_dice: 1, die_value: 6, type: "piercing" },
      { num_dice: 1, die_value: 8, type: "piercing", versatile: true },
    ],
    normal_range: 20,
    long_range: 60,
    martial: true,
  },
  {
    name: "War pick",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    martial: true,
  },
  {
    name: "Warhammer",
    category: "weapon",
    weapon_type: "melee",
    damage: [
      { num_dice: 1, die_value: 8, type: "bludgeoning" },
      { num_dice: 1, die_value: 10, type: "bludgeoning", versatile: true },
    ],
    martial: true,
  },
  {
    name: "Whip",
    category: "weapon",
    weapon_type: "melee",
    damage: [{ num_dice: 1, die_value: 4, type: "slashing" }],
    finesse: true,
    martial: true,
    reach: true,
  },

  // Martial Ranged Weapons
  {
    name: "Blowgun",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 1, type: "piercing" }],
    normal_range: 25,
    long_range: 100,
    starting_ammo: 50,
    martial: true,
    ammunition: true,
    loading: true,
  },
  {
    name: "Crossbow, hand",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 6, type: "piercing" }],
    normal_range: 30,
    long_range: 120,
    starting_ammo: 20,
    martial: true,
    ammunition: true,
    light: true,
    loading: true,
  },
  {
    name: "Crossbow, heavy",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 10, type: "piercing" }],
    normal_range: 100,
    long_range: 400,
    starting_ammo: 20,
    martial: true,
    ammunition: true,
    heavy: true,
    loading: true,
    two_handed: true,
  },
  {
    name: "Longbow",
    category: "weapon",
    weapon_type: "ranged",
    damage: [{ num_dice: 1, die_value: 8, type: "piercing" }],
    normal_range: 150,
    long_range: 600,
    starting_ammo: 20,
    martial: true,
    ammunition: true,
    heavy: true,
    two_handed: true,
  },
  {
    name: "Net",
    category: "weapon",
    weapon_type: "thrown",
    damage: [],
    normal_range: 5,
    long_range: 15,
    martial: true,
  },
]
